'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const BASE='C:/Users/runge/.nevermonday-secrets/ios16-protected-github-macos-source-20261006',PRIMARY='C:/Users/runge/.nevermonday-secrets/ios16-protected-github-macos-context-20261006';
const P=require('./policy.cjs'),E=require('./envelope.cjs'),I=require('./payload.cjs'),J=require('./job.cjs'),R=require('./runner.cjs'),C=require('./private-capture.cjs'),Probe=require('./macos-probe.cjs'),F=require('./fixtures.cjs');
function source(file,expected){const b=fs.readFileSync(file);if(expected)assert.equal(P.sha(b),expected);return b.toString('utf8');}
function evaluate(code,modules,dirname,environment={}){const m={exports:{}};const load=n=>{if(Object.hasOwn(modules,n))return modules[n];throw Error('UNEXPECTED_PUBLIC_IMPORT');};new Function('require','module','exports','__dirname','process',code)(load,m,m.exports,dirname,{execPath:process.execPath,execArgv:[],env:environment,platform:process.platform});return m.exports;}
function plugin(job,baseEnv){const calls={clients:0,builder:0,filesystem:0,network:0,removed:[],ctx:null,options:null},logger={info(){},warn(){},error(){},level:()=>30,child(){return this;}},logBuffer={getPhaseLogs:()=>[]};
 const enums={...require('C:/Users/runge/AppData/Local/npm-cache/_npx/6bc7bae5c2059953/node_modules/@expo/eas-build-job'),version:'24.8.0'};
 const contextCode=source(PRIMARY+'/dist/context.js','fbcfc397add65cdf71c55704a4c172ad8848a91223462747004b562520438d0e');
 const allocations={Client:class{constructor(v){calls.clients++;calls.options=v;assert.equal(v.url,'https://api.expo.dev/graphql');this.url=v.url;}},fetchExchange:()=>{calls.network++;throw Error('NO_NETWORK');}};
 const Context=evaluate(contextCode,{'@expo/eas-build-job':enums,'@expo/eas-build-job/dist/common':enums,'@urql/core':allocations,'fs-extra':{readdir:async()=>[],readFile:()=>{calls.filesystem++;throw Error('NO_FILES');},remove:()=>{calls.filesystem++;throw Error('NO_FILES');}},path:path.posix,'./buildErrors/detectError':{resolveBuildPhaseErrorAsync:e=>e},'./datadog':{Datadog:{distribution(){}}},'./utils/appConfig':{},'./utils/environmentSecrets':{createTemporaryEnvironmentSecretFile(){calls.filesystem++;throw Error('NO_FILES');}},'./utils/packageManager':{}},PRIMARY);
 const config={skipNativeBuild:false,skipCleanup:false},buildTools={...Context,Builders:{iosBuilder:async ctx=>{calls.builder++;calls.ctx=ctx;return ctx.artifacts;}}};
 const ios=evaluate(source(BASE+'/plugin-source/dist/ios.js','4321768f06a1fde963512798db4bee54c4977b181029ff4fac379616b8a37ae9'),{'@expo/build-tools':buildTools,'@expo/eas-build-job':enums,'lodash/omit':(v,k)=>Object.fromEntries(Object.entries(v).filter(([n])=>n!==k)),'./artifacts':{prepareArtifacts:()=>{throw Error('NO_ARTIFACTS');}},'./config':config,'./logger':{logBuffer}},BASE+'/plugin-source/dist');
 const build=evaluate(source(BASE+'/plugin-source/dist/build.js','efe24dda4554bc7d7c7995b0f9c4ebc347b1b8e31be53fcd0bc9aa97e2afac65'),{'@expo/build-tools':buildTools,'@expo/eas-build-job':enums,'@expo/bunyan':{DEBUG:20},chalk:{green:s=>s,red:s=>s,yellow:s=>s},'fs-extra':{remove:async p=>calls.removed.push(p)},'lodash/pickBy':(v,predicate)=>Object.fromEntries(Object.entries(v).filter(([,x])=>predicate(x))),path:path.posix,'./android':{buildAndroidAsync:()=>{throw Error('NO_ANDROID');}},'./config':config,'./ios':ios,'./logger':{createLogger:()=>logger},'./workingdir':{prepareWorkingdirAsync:async()=>'/Users/runner/work/_temp/context-fixture'}},BASE+'/plugin-source/dist',baseEnv);
 return{calls,Context,run:()=>build.buildAsync(job,{username:P.ACCOUNT,buildProfile:'protected-local-ci16',gitCommitHash:P.SOURCE}),async quiet(){const original={};for(const k of ['log','warn','error','info']){original[k]=console[k];console[k]=()=>{};}try{return await this.run();}finally{for(const[k,v]of Object.entries(original))console[k]=v;}}};
}
function job(){return J.render({p12:Buffer.from('synthetic-p12'),cms:Buffer.from('synthetic-cms'),password:'synthetic-only'},'/Users/runner/work/_temp/context-fixture/project.tgz',F.OWNER,F.publicEnv,'/Users/runner/work/_temp/context-fixture',x=>x).job;}
test('exact locked real BuildContext constructor reproduces missing API base before Client/builder/files',()=>{const p=plugin(job(),{});assert.throws(()=>new p.Context.BuildContext(job(),{workingdir:'/Users/runner/work/_temp/context-fixture',logger:{},env:{},metadata:{}}),{code:'ERR_INVALID_URL'});assert.equal(p.calls.clients,0);assert.equal(p.calls.builder,0);assert.equal(p.calls.filesystem,0);assert.equal(p.calls.network,0);});
test('whole official plugin build→ios→unmodified Context forwards fixed production base without auth/network',async()=>{const p=plugin(job(),C.environment({PATH:'/usr/bin',HOME:'/Users/runner'},{__API_SERVER_URL:'https://api.expo.dev'}));await p.quiet();assert.equal(p.calls.builder,1);assert.equal(p.calls.clients,1);assert.equal(p.calls.ctx.env.__API_SERVER_URL,'https://api.expo.dev');assert.equal(p.calls.ctx.isLocal,true);assert.equal(p.calls.ctx.job.secrets.robotAccessToken,undefined);assert.equal(p.calls.options.fetchOptions.headers.Authorization,'Bearer undefined');assert.equal(p.calls.network,0);assert.equal(p.calls.filesystem,0);assert.ok(p.calls.removed.includes(job().projectArchive.path));});
test('whole official plugin with original omission rejects before builder and retains cleanup path',async()=>{const p=plugin(job(),C.environment({PATH:'/usr/bin'}));await assert.rejects(()=>p.quiet(),{code:'ERR_INVALID_URL'});assert.equal(p.calls.builder,0);assert.equal(p.calls.clients,0);assert.equal(p.calls.network,0);assert.equal(p.calls.removed.length,2);});
function chain(){const text=source(__dirname+'/chain.test.cjs'),a=text.indexOf('function fixture(){'),z=text.indexOf("test('whole real runner",a),prefix=text.slice(a,z);return new Function('require','P','E','I','J','R','Recv','C','Probe','F','fs','path','crypto','assert','__dirname',prefix+'return{fixture,runnerPorts};')(require,P,E,I,J,R,require('./receiver.cjs'),C,Probe,F,fs,path,crypto,assert,__dirname);}
function originalRunner(){return evaluate(source(BASE+'/runner.cjs','c12b163e17f627becbbf18d3c4d091e3b9d5a49fbea45bed68d3a57dd6b17c21'),{'node:fs':fs,'node:path':path,'node:crypto':crypto},BASE);}
async function captured(runner){const f=chain().fixture(),x=chain().runnerPorts(f),old=x.ports.run;let observed; x.ports.run=async(file,args,o)=>{if(file===process.execPath&&args.length===1&&args[0].endsWith('/eas-cli-local-build-plugin/bin/run')){const raw=JSON.parse(Buffer.from(o.env.EAS_LOCAL_BUILD_PLUGIN_INPUT,'base64').toString()),p=plugin(raw.job,o.env);observed=p;try{await p.quiet();}catch(e){return{status:1,error:false,signal:null,stdout:Buffer.alloc(0),stderr:Buffer.from(e.code==='ERR_INVALID_URL'?'SYNTHETIC_INVALID_URL':'SYNTHETIC_FAILURE')};}}return old(file,args,o);};let out,error;try{out=await runner.perform(f.input,f.key,x.m,f.env,x.ports);}catch(e){error=e;}return{out,error,observed,calls:x.calls};}
test('actual saved successor Runner.perform reaches whole public plugin/Context with normalized URL',async()=>{const v=await captured(R);assert.equal(v.out.sourceVerified,true);assert.equal(v.observed.calls.ctx.graphqlClient.url,'https://api.expo.dev/graphql');assert.equal(v.observed.calls.network,0);assert.equal(v.observed.calls.builder,1);assert.equal(v.calls.at(-1),'CLEANUP');});
test('actual frozen179 Runner.perform reproduces precompiler failure through whole same public closure',async()=>{const v=await captured(originalRunner());assert.equal(v.out,undefined);assert.equal(v.error.privateOutput.kind,'ROOT_CI16_PRIVATE_BUILD_FAILURE');assert.equal(v.observed.calls.builder,0);assert.equal(v.observed.calls.clients,0);assert.equal(v.observed.calls.network,0);assert.equal(v.calls.at(-1),'CLEANUP');});
test('whole runner source changes exactly one public normalization literal; job/receiver remain exact',()=>{const old=source(BASE+'/runner.cjs'),from='{EAS_LOCAL_BUILD_PLUGIN_INPUT:jobRaw.toString(',to="{__API_SERVER_URL:'https://api.expo.dev',EAS_LOCAL_BUILD_PLUGIN_INPUT:jobRaw.toString(";assert.equal(old.split(from).length,2);assert.equal(source(__dirname+'/runner.cjs'),old.replace(from,to));for(const f of ['job.cjs','receiver.cjs','private-capture.cjs','lineage.cjs','protected-ios16.yml'])assert.ok(fs.readFileSync(BASE+'/'+f).equals(fs.readFileSync(__dirname+'/'+f)));});
test('normalization follows exact primary CLI route and never copies an ambient arbitrary API base',()=>{const sdk='C:/Users/runge/AppData/Local/npm-cache/_npx/6bc7bae5c2059953/node_modules/eas-cli/build/build/local.js',s=source(sdk,'8e981cd7a85c05414d7de4671ea721288e975f556edee0f0e0b21260f35b78fb');assert.ok(s.includes('__API_SERVER_URL: (0, api_1.getExpoApiBaseUrl)()'));const e=C.environment({__API_SERVER_URL:'https://evil.invalid',EXPO_TOKEN:'fictional',EAS_TOKEN:'fictional'},{__API_SERVER_URL:'https://api.expo.dev'});assert.equal(e.__API_SERVER_URL,'https://api.expo.dev');assert.equal(e.EXPO_TOKEN,undefined);assert.equal(e.EAS_TOKEN,undefined);});
test('new approval refuses spent old operation and history reader has no implicit private reads',()=>{const H=require('./failed-operation.cjs'),a=F.approval();a.operationId=H.OLD_ID;a.environmentName='nm-ios16-'+a.operationId;assert.throws(()=>P.approval(a,F.NOW));assert.equal(H.ROWS.length,7);assert.equal(H.ASSETS.claim.bytes,933);assert.throws(()=>H.hold());assert.throws(()=>H.hold(()=>Buffer.from('fictional wrong history')));});
