'use strict';
const crypto=require('node:crypto'),P=require('./policy.cjs');
const MAX_BYTES=268435456;
function context(v){if(!P.exact(v,['operationId','direction','workflowCommit','sourceReviewSha256','nativeSource','backendSource','version']))P.fail();header({kind:'ROOT_PROTECTED_IOS16_AEAD_ENVELOPE',...v,payloadBytes:1,payloadSha256:'0'.repeat(64)});return v;}
function header(v){if(!P.exact(v,['kind','operationId','direction','workflowCommit','sourceReviewSha256','nativeSource','backendSource','version','payloadBytes','payloadSha256'])||v.kind!=='ROOT_PROTECTED_IOS16_AEAD_ENVELOPE'||!P.UUID.test(v.operationId)||!['INPUT','CLAIM','OUTPUT'].includes(v.direction)||!P.GIT.test(v.workflowCommit)||!P.SHA.test(v.sourceReviewSha256)||v.nativeSource!==P.SOURCE||v.backendSource!==P.BACKEND_SOURCE||v.version!==16||!Number.isSafeInteger(v.payloadBytes)||v.payloadBytes<1||v.payloadBytes>MAX_BYTES||!P.SHA.test(v.payloadSha256))P.fail();return Buffer.from(JSON.stringify(P.canonical(v)));}
function subkey(key,v){if(!Buffer.isBuffer(key)||key.length!==32)P.fail();return Buffer.from(crypto.hkdfSync('sha256',key,Buffer.from(v.operationId),Buffer.from('nm-ios16:'+v.direction+':'+v.workflowCommit),32));}
function seal(payload,key,expected,nonce){context(expected);if(!Buffer.isBuffer(payload)||payload.length<1||payload.length>MAX_BYTES||!Buffer.isBuffer(nonce)||nonce.length!==12)P.fail();const h={kind:'ROOT_PROTECTED_IOS16_AEAD_ENVELOPE',...expected,payloadBytes:payload.length,payloadSha256:P.sha(payload)},aad=header(h),k=subkey(key,h);try{const c=crypto.createCipheriv('aes-256-gcm',k,nonce);c.setAAD(aad);const cipher=Buffer.concat([c.update(payload),c.final()]),tag=c.getAuthTag();return {header:h,nonce:nonce.toString('base64'),tag:tag.toString('base64'),ciphertext:cipher.toString('base64')};}finally{k.fill(0);}}
function base64(v,max){if(typeof v!=='string'||v.length<1||v.length>max*2||!/^[A-Za-z0-9+/]+={0,2}$/.test(v))P.fail();const b=Buffer.from(v,'base64');if(b.length>max||b.toString('base64')!==v)P.fail();return b;}
function open(v,key,expected){context(expected);if(!P.exact(v,['header','nonce','tag','ciphertext']))P.fail();const aad=header(v.header);for(const [k,value]of Object.entries(expected))if(v.header[k]!==value)P.fail();const n=base64(v.nonce,12),tag=base64(v.tag,16),b=base64(v.ciphertext,MAX_BYTES);if(n.length!==12||tag.length!==16||b.length!==v.header.payloadBytes)P.fail();const k=subkey(key,v.header);try{const c=crypto.createDecipheriv('aes-256-gcm',k,n);c.setAAD(aad);c.setAuthTag(tag);const plain=Buffer.concat([c.update(b),c.final()]);if(plain.length!==v.header.payloadBytes||P.sha(plain)!==v.header.payloadSha256){plain.fill(0);P.fail();}return plain;}catch{P.fail();}finally{k.fill(0);}}
module.exports={MAX_BYTES,context,header,subkey,seal,open};
