'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto'),H=require('./held-source.cjs');
const ROOT=__dirname,NODE='C:/Users/runge/.nevermonday-secrets/public-node22-qa-tools-20261005/extracted/node-v22.23.3-win-x64/node.exe',PS='C:/Users/runge/.cache/codex-runtimes/codex-primary-runtime/dependencies/native/powershell/pwsh.exe',PY='C:/Users/runge/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe';
const FILES=Object.freeze(['policy.cjs','envelope.cjs','export-query.cjs','transport.cjs','exporter.cjs','metadata-policy.cjs','source-bundle.cjs','public-source-manifest.json','job.cjs','payload.cjs','private-capture.cjs','held-source.cjs','bootstrap.cjs','github-release.cjs','signer-check.ps1','runner.cjs','protected-ios16.yml','receiver.cjs','root-export.cjs','root-github.cjs','root-receive.cjs','lineage.cjs','fixtures.cjs','helpers.test.cjs','chain.test.cjs','lineage.test.cjs','crypto.test.cjs','crypto-fixtures.ps1','native-audit.py','native-byte.test.py','ipa-cms-check.ps1','artifact_guard.py','feature_guard.py','brightness_guard.py','lucky_days_guard.py','notifications_guard.py','icon_guard.py','README.md','approval-template.json','build-input-template.json','runtime-package.json','runtime-package-lock.json','local-plugin-public.json','plugin-public-source-pins.json','source-dependencies.json','macos-probe.cjs','publication.cjs','context.test.cjs','failed-operation.cjs','failed-operation-c0a.cjs','audit-diagnostic.test.cjs','audit-diagnostic.test.py','failed-operation-f895.cjs','runtime-config.test.cjs','runtime-config.test.py','prepare-review.cjs']);
const TESTS=Object.freeze(['helpers.test.cjs','chain.test.cjs','lineage.test.cjs','crypto.test.cjs','context.test.cjs','audit-diagnostic.test.cjs','runtime-config.test.cjs']);
function collect(){return FILES.map(file=>{const b=H.read(path.join(ROOT,file),2000000);return{file,bytes:b.length,sha256:H.sha(b)};});}
function env(){const e={};for(const k of ['SystemRoot','WINDIR','TEMP','TMP','COMSPEC','PATHEXT'])if(process.env[k])e[k]=process.env[k];e.PATH=path.dirname(NODE)+';C:/Program Files/Git/cmd;C:/Windows/System32';e.CI='true';return e;}
function observe(file,args,options={}){const id=crypto.randomUUID(),before=collect(),deps=JSON.parse(H.read(path.join(ROOT,'source-dependencies.json'),200000)),held=H.hold([...before,...deps],ROOT),startedAt=new Date().toISOString();const r=cp.spawnSync(file,args,{cwd:ROOT,env:env(),shell:false,encoding:null,timeout:300000,maxBuffer:16*1024*1024,windowsHide:true,...options});const stdout=r.stdout||Buffer.alloc(0),stderr=r.stderr||Buffer.alloc(0);fs.writeFileSync(path.join(ROOT,'source-gate-'+id+'.stdout'),stdout,{flag:'wx'});fs.writeFileSync(path.join(ROOT,'source-gate-'+id+'.stderr'),stderr,{flag:'wx'});H.check(held);const proof={id,startedAt,finishedAt:new Date().toISOString(),status:r.status,error:!!r.error,signal:r.signal,stdoutBytes:stdout.length,stdoutSha256:H.sha(stdout),stderrBytes:stderr.length,stderrSha256:H.sha(stderr),sourceRows:held.length,actualInputsRead:0,credentialReads:0,providerOperations:0,actualJobs:0};fs.writeFileSync(path.join(ROOT,'source-gate-'+id+'.json'),JSON.stringify(proof,null,2)+'\n',{flag:'wx'});return{proof,stdout,stderr,before,deps};}
function gate(){const r=observe(NODE,['--test','--test-concurrency=1','--test-reporter=tap',...TESTS]);const text=r.stdout.toString('utf8'),counts={};for(const key of ['tests','pass','fail','cancelled','skipped','todo']){const m=new RegExp('^# '+key+' (\\d+)$','m').exec(text);if(!m)throw Error('SOURCE_TEST_CENSUS_REFUSED');counts[key]=Number(m[1]);}if(r.proof.status!==0||r.proof.error||r.proof.signal||r.stderr.length||counts.tests!==151||counts.pass!==counts.tests||['fail','cancelled','skipped','todo'].some(k=>counts[k]!==0))throw Error('SOURCE_TEST_GATE_REFUSED');const syntax=[];for(const file of FILES.filter(x=>x.endsWith('.cjs'))){const s=observe(NODE,['--check',file]);if(s.proof.status!==0||s.proof.error||s.proof.signal||s.stdout.length||s.stderr.length)throw Error('SOURCE_SYNTAX_REFUSED');syntax.push({file,proof:s.proof});}const p=observe(PY,['runtime-config.test.py']);if(p.proof.status!==0||p.proof.error||p.proof.signal||p.stdout.length||!/^\.{45}\r?\n[-]+\r?\nRan 45 tests in [0-9.]+s\r?\n\r?\nOK\r?\n$/.test(p.stderr.toString('utf8')))throw Error('SOURCE_NATIVE_BYTE_TEST_REFUSED');return{tests:counts,proof:r.proof,syntax,python:p.proof,files:r.before,sourceDependencies:r.deps};}
function main(args=[]){if(args.length===0)return{preparedOnly:true,actualInputsRead:0,actualOperations:0};if(args.length!==1||!['--gate','--seal'].includes(args[0]))throw Error('SOURCE_MODE_REFUSED');const v=gate();if(args[0]==='--seal'){const files=collect(),sourceDependencies=JSON.parse(H.read(path.join(ROOT,'source-dependencies.json'),200000)),aggregate=H.sha(Buffer.from(JSON.stringify(files))),review={kind:'ROOT_PROTECTED_IOS16_SOURCE_REVIEW',preparedAt:new Date().toISOString(),sourceOnly:true,actualInputsRead:0,credentialReads:0,providerOperations:0,actualJobs:0,files,sourceDependencies,aggregateSha256:aggregate,tests:v.tests,syntaxFiles:v.syntax.map(s=>s.file),directGateProof:v.proof,pythonProof:v.python,fullIndependentPeerRequired:true,actualAuthorization:false};fs.writeFileSync(path.join(ROOT,'source-review.json'),JSON.stringify(review,null,2)+'\n',{flag:'wx'});return{receiptSha256:H.sha(fs.readFileSync(path.join(ROOT,'source-review.json'))),aggregateSha256:aggregate,files:files.length,dependencies:sourceDependencies.length,tests:v.tests,syntax:v.syntax.length,pythonTests:45,gateProof:v.proof};}return{tests:v.tests,syntax:v.syntax.length,pythonTests:45,gateProof:v.proof};}
module.exports={ROOT,NODE,PS,PY,FILES,TESTS,collect,env,observe,gate,main};
if(require.main===module){try{process.stdout.write(JSON.stringify(main(process.argv.slice(2)))+'\n');}catch{process.stdout.write('{"sourceGate":false,"actualOperations":0}\n');process.exitCode=1;}}
