'use strict';
// Root-only explicit export. Import/default does not inspect auth or any input.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),cp=require('node:child_process');
const ROOT=__dirname,SDK='C:/Users/runge/AppData/Local/npm-cache/_npx/6bc7bae5c2059953/node_modules/eas-cli';
const WORKSPACE='C:/Users/runge/Desktop/nevermonday app',PRIVATE=path.join(ROOT,'protected');
function refuse(){throw Error('ROOT_PROTECTED_EXPORT_REFUSED');}
function pre(env,args){if(args.length||['NODE_OPTIONS','NODE_DEBUG','NODE_DEBUG_NATIVE','DEBUG','RUST_LOG'].some(k=>env[k]!==undefined&&env[k]!==''))refuse();}
function initial(file,max){const l=fs.lstatSync(file);if(!l.isFile()||l.isSymbolicLink()||l.nlink!==1||l.size<1||l.size>max)refuse();const b=fs.readFileSync(file);if(b.length!==l.size)refuse();return b;}
async function execute(id,ports={}){
 pre(ports.env||process.env,process.execArgv);if(!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(id))refuse();
 const dir=path.join(PRIVATE,id),a=JSON.parse(initial(path.join(dir,'approval.json'),32000)),reviewRaw=initial(path.join(ROOT,'source-review.json'),2000000),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
 if(hash(reviewRaw)!==a.sourceReviewSha256)refuse();const review=JSON.parse(reviewRaw),row=review.files?.find(x=>x.file==='bootstrap.cjs');if(!row||hash(initial(path.join(ROOT,'bootstrap.cjs'),row.bytes))!==row.sha256)refuse();
 const B=require('./bootstrap.cjs'),held=B.hold(ROOT,a.sourceReviewSha256),P=require('./policy.cjs'),H=require('./held-source.cjs'),Q=require('./export-query.cjs'),E=require('./envelope.cjs'),S=require('./source-bundle.cjs'),I=require('./payload.cjs'),X=require('./exporter.cjs'),T=require('./transport.cjs'),Old=require('./metadata-policy.cjs');
 H.startup(ports.env||process.env,[]);P.approval(a,Date.now());if(a.operationId!==id)refuse();const deps=H.hold(review.sourceDependencies,ROOT);const history=require('./failed-operation-9c.cjs').holdAll(H.read);const check=()=>{held.check();H.check(deps);require('./failed-operation-9c.cjs').same(history,H.read);};check();
 const config=JSON.parse(H.read(path.join(dir,'build-input.json'),32000));if(!P.exact(config,['publicEnv'])||fs.existsSync(path.join(dir,'export-once.json'))||fs.existsSync(inputFile(dir,id))||fs.existsSync(path.join(dir,'key.bin')))refuse();
 const manifestRaw=H.read(path.join(ROOT,'public-source-manifest.json'),200000),manifest=JSON.parse(manifestRaw);if(P.sha(manifestRaw)!==a.publicSourceManifestSha256)refuse();
 const files=S.gitFiles(manifest,(commit,file)=>{check();const r=cp.spawnSync('git',['show',commit+':'+file],{cwd:WORKSPACE,env:rootEnvironment(process.env),shell:false,encoding:null,maxBuffer:16*1024*1024,timeout:30000,windowsHide:true});if(r.status!==0||r.error||r.signal||r.stderr.length)refuse();return r.stdout;});S.verifyFiles(manifest,files);check();
 const sdkRead=file=>require(path.join(SDK,file));let ownerId=null;
 const auth=()=>existingAuth(sdkRead);
 const key=crypto.randomBytes(32);try{return await X.exportSigner(a,{now:Date.now,check,metadataPolicy:Old,reserve:()=>fs.writeFileSync(path.join(dir,'export-once.json'),JSON.stringify({operationId:id,startedAt:new Date().toISOString(),noAutomaticRetry:true})+'\n',{flag:'wx',mode:0o600}),auth,query:async(kind,identifier,credential,deadline)=>{const v=await T.query(kind,identifier,credential,deadline);if(kind==='IDENTITY')ownerId=Old.discover(v,a).ownerId;return v;},validateMaterial:async(material)=>{check();const input={p12:material.p12.toString('base64'),cms:material.cms.toString('base64'),password:material.password,certificateSerialSha256:a.certificateSerialSha256,profileUuidSha256:a.profileUuidSha256,team:P.TEAM,bundle:P.BUNDLE};const r=cp.spawnSync('C:/Users/runge/.cache/codex-runtimes/codex-primary-runtime/dependencies/native/powershell/pwsh.exe',['-NoLogo','-NoProfile','-NonInteractive','-File',path.join(ROOT,'signer-check.ps1')],{input:JSON.stringify(input),env:rootEnvironment(process.env),shell:false,encoding:null,maxBuffer:65536,timeout:60000,windowsHide:true});input.password=null;check();if(r.status!==0||r.error||r.signal||r.stderr.length)refuse();return JSON.parse(r.stdout.toString('utf8'));},sealPackage:async(material)=>{check();const plain=I.packageInput(a,manifest,files,material,config.publicEnv,ownerId,H.sha(H.read(path.join(ROOT,'runtime-package-lock.json'),2000000))),ctx={operationId:id,direction:'INPUT',workflowCommit:a.workflowCommit,sourceReviewSha256:a.sourceReviewSha256,nativeSource:P.SOURCE,backendSource:P.BACKEND_SOURCE,version:16};try{const cipher=Buffer.from(JSON.stringify(E.seal(plain,key,ctx,crypto.randomBytes(12))));fs.writeFileSync(path.join(dir,'key.bin'),key,{flag:'wx',mode:0o600});fs.writeFileSync(inputFile(dir,id),cipher,{flag:'wx',mode:0o600});return{operationId:id,cipherSha256:P.sha(cipher),cipherBytes:cipher.length,sourceManifestSha256:a.publicSourceManifestSha256,plaintextSavedPublic:false,signerSavedPublic:false,keySavedPublic:false};}finally{plain.fill(0);}},record:v=>fs.writeFileSync(path.join(dir,'export-result.json'),JSON.stringify(v)+'\n',{flag:'wx',mode:0o600})});}finally{key.fill(0);ownerId=null;}
}
function rootEnvironment(v){const e={};for(const k of ['SystemRoot','WINDIR','USERPROFILE','APPDATA','LOCALAPPDATA','TEMP','TMP','COMSPEC','PATHEXT'])if(typeof v[k]==='string')e[k]=v[k];e.PATH=path.dirname(process.execPath)+';C:/Program Files/Git/cmd;C:/Windows/System32';return e;}
function existingAuth(load){if(load('build/api.js').getExpoApiBaseUrl()!=='https://api.expo.dev')refuse();const Manager=load('build/user/SessionManager.js').default,s=new Manager(null),token=s.getAccessToken(),type=token===null?'sessionSecret':'accessToken',value=type==='accessToken'?token:s.getSessionSecret();if(typeof value!=='string'||value.length<1||value.length>4096||/[\x00-\x20\x7f]/.test(value))refuse();return{type,value};}
function main(args=[]){if(args.length===0)return Promise.resolve({preparedOnly:true,credentialReads:0,credentialQueries:0,jobs:0});if(args.length===2&&args[0]==='--export')return execute(args[1]);refuse();}
function inputFile(dir,id){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(id))throw Error('INPUT_NAME_REFUSED');return path.join(dir,'input-'+id+'.nmae');}
module.exports={inputFile,SDK,WORKSPACE,PRIVATE,pre,rootEnvironment,existingAuth,execute,main};
if(require.main===module)main(process.argv.slice(2)).then(v=>process.stdout.write(JSON.stringify(v)+'\n')).catch(()=>{process.stdout.write('{"protectedExport":false,"detailsSuppressed":true}\n');process.exitCode=1;});
