'use strict';
// Fixed existing-repository operations for Root only. No account, paid plan,
// upload-artifact/cache/package API, reusable Expo token or automatic retries.
const cp=require('node:child_process'),P=require('./policy.cjs'),H=require('./held-source.cjs'),R=require('./root-export.cjs');
const GH='C:/Program Files/GitHub CLI/gh.exe';
function cli(args,input,ports={}){if(typeof ports.check!=='function')P.fail();ports.check();const invoke=ports.invoke||cp.spawnSync,r=invoke(GH,args,{input,env:R.rootEnvironment(process.env),shell:false,encoding:null,timeout:60000,maxBuffer:8*1024*1024,windowsHide:true});ports.check();if(r.status!==0||r.error||r.signal||r.stderr.length)P.fail();return r.stdout;}
function api(method,endpoint,body,ports){const args=['api','--method',method,endpoint];if(body!==undefined)args.push('--input','-');return JSON.parse(cli(args,body===undefined?undefined:JSON.stringify(body),ports).toString('utf8'));}
async function placeAndDispatch(a,current,key,releaseId,inputAsset,ports){P.approval(a,ports.now());P.repository(current,ports.now());if(current.refSha!==a.workflowCommit||!Buffer.isBuffer(key)||key.length!==32||!P.exact(inputAsset,['assetId','cipherSha256','cipherBytes'])||!Number.isSafeInteger(releaseId)||releaseId<1)P.fail();ports.check();ports.verifyRemoteSourceAndTag();P.approval(a,ports.now());ports.reserve(a.operationId);const repo='/repos/'+P.REPOSITORY,environment=a.environmentName,tag='nm-ios16-'+a.operationId;
 // Root must first create the one cipher-only prerelease at workflowCommit and
 // verify its new tag/ref. Existing names or any alternate workflows refuse.
 await ports.environmentMustBeAbsent(environment);api('PUT',repo+'/environments/'+environment,{deployment_branch_policy:{protected_branches:false,custom_branch_policies:true}},ports);api('POST',repo+'/environments/'+environment+'/deployment-branch-policies',{name:tag,type:'tag'},ports);await ports.verifyEnvironmentPolicy(environment,tag);ports.check();ports.verifyRemoteSourceAndTag();P.approval(a,ports.now());
 cli(['secret','set','NM_CI_AES_KEY','--env',environment,'--repo',P.REPOSITORY],key.toString('base64'),ports);await ports.verifySecretNameOnly(environment,'NM_CI_AES_KEY');ports.check();ports.verifyRemoteSourceAndTag();P.approval(a,ports.now());
 const inputs={operation_id:a.operationId,workflow_sha:a.workflowCommit,source_review_sha:a.sourceReviewSha256,environment_name:environment,release_id:String(releaseId),input_asset_id:String(inputAsset.assetId),input_cipher_sha:inputAsset.cipherSha256,input_cipher_bytes:String(inputAsset.cipherBytes)};
 // gh run returns204 with empty output; no assumed run ID/success.
 const args=['api','--method','POST',repo+'/actions/workflows/nm-protected-ios16.yml/dispatches','--input','-'];cli(args,JSON.stringify({ref:tag,inputs}),ports);ports.record({kind:'ROOT_PROTECTED_CI16_DISPATCH_ACKNOWLEDGED',operationId:a.operationId,workflowCommit:a.workflowCommit,tag,environmentName:environment,dispatchAcknowledged:true,buildVerified:false,freeStandardPublicRunnerOnly:true,noAutomaticRetry:true});
}
async function deleteKey(a,ports){ports.check();cli(['secret','delete','NM_CI_AES_KEY','--env',a.environmentName,'--repo',P.REPOSITORY],undefined,ports);await ports.verifySecretAbsent(a.environmentName,'NM_CI_AES_KEY');ports.check();ports.record({kind:'ROOT_CI16_EPHEMERAL_SECRET_DELETED',operationId:a.operationId,secretAbsentVerified:true});}
function sourceBytes(file,commit,ports){const v=api('GET','/repos/'+P.REPOSITORY+'/contents/'+file+'?ref='+commit,undefined,ports);if(v.type!=='file'||v.encoding!=='base64'||typeof v.content!=='string')P.fail();const b=Buffer.from(v.content.replace(/\n/g,''),'base64');if(b.length!==v.size||b.length>2000000)P.fail();return b;}
function preflight(a,review,ports={},requireTag=true){const observedAt=new Date().toISOString(),repo='/repos/'+P.REPOSITORY,u=api('GET','/user',undefined,ports),v=api('GET',repo,undefined,ports),p=api('GET',repo+'/actions/permissions',undefined,ports),c=api('GET',repo+'/collaborators?per_page=100',undefined,ports),invitations=api('GET',repo+'/invitations?per_page=100',undefined,ports),ref=api('GET',repo+'/git/ref/'+(requireTag?'tags/nm-ios16-'+a.operationId:'heads/main'),undefined,ports),workflows=api('GET',repo+'/actions/workflows?per_page=100',undefined,ports);if(u.login!==P.ACTOR||v.full_name!==P.REPOSITORY||v.private!==false||v.archived!==false||v.disabled!==false||v.permissions?.admin!==true||p.enabled!==true||p.allowed_actions!=='all'||!Array.isArray(c)||c.length!==1||c[0].login!==P.ACTOR||c[0].permissions?.admin!==true||!Array.isArray(invitations)||invitations.length!==0||ref.object?.type!=='commit'||ref.object.sha!==a.workflowCommit||workflows.total_count!==2||workflows.workflows?.length!==2)P.fail();const names=workflows.workflows.map(v=>v.path).sort();if(names.join('|')!==['.github/workflows/nm-ios16-toolchain-probe.yml','.github/workflows/nm-protected-ios16.yml'].join('|'))P.fail();if(H.sha(sourceBytes(names[0],a.workflowCommit,ports))!=='0a344f726b6d9ce817f0efeb4a63b77488614c56b6f3b80ca60515a66cc09be8')P.fail();for(const r of review.files){const file='.github/protected-ios16/'+r.file,b=sourceBytes(file,a.workflowCommit,ports);if(b.length!==r.bytes||H.sha(b)!==r.sha256)P.fail();}if(H.sha(sourceBytes('.github/protected-ios16/source-review.json',a.workflowCommit,ports))!==a.sourceReviewSha256)P.fail();const workflowRow=review.files.find(x=>x.file==='protected-ios16.yml');if(!workflowRow||H.sha(sourceBytes('.github/workflows/nm-protected-ios16.yml',a.workflowCommit,ports))!==workflowRow.sha256)P.fail();return{repository:P.REPOSITORY,public:true,archived:false,disabled:false,admin:true,actionsEnabled:true,unexpectedWriters:0,workflowsReviewed:true,refSha:a.workflowCommit,observedAt};}
function createCipherRelease(a,current,file,ports){P.approval(a,ports.now());P.repository(current,ports.now());if(current.refSha!==a.workflowCommit||typeof file!=='string'||!file.endsWith('/protected/'+a.operationId+'/input-'+a.operationId+'.nmae')&&!file.endsWith('\\protected\\'+a.operationId+'\\input-'+a.operationId+'.nmae'))P.fail();ports.check();ports.requireTagAndReleaseAbsent();const b=H.read(file,400*1024*1024),tag='nm-ios16-'+a.operationId,v=api('POST','/repos/'+P.REPOSITORY+'/releases',{tag_name:tag,target_commitish:a.workflowCommit,name:tag,body:'Encrypted per-operation CI input/output only. No plaintext application artifact.',draft:false,prerelease:true},ports);if(!Number.isSafeInteger(v.id)||v.id<1||v.tag_name!==tag||v.target_commitish!==a.workflowCommit)P.fail();ports.verifyRemoteSourceAndTag();P.approval(a,ports.now());cli(['release','upload',tag,file,'--repo',P.REPOSITORY],undefined,ports);const after=api('GET','/repos/'+P.REPOSITORY+'/releases/'+v.id,undefined,ports);const assets=after.assets.filter(x=>x.name==='input-'+a.operationId+'.nmae');if(assets.length!==1||assets[0].size!==b.length||assets[0].state!=='uploaded'||assets[0].digest&&assets[0].digest!=='sha256:'+H.sha(b))P.fail();ports.check();if(H.sha(H.read(file,400*1024*1024))!==H.sha(b))P.fail();return{releaseId:v.id,inputAsset:{assetId:assets[0].id,cipherSha256:H.sha(b),cipherBytes:b.length}};}
function verifyEnvironment(a,ports={}){const base='/repos/'+P.REPOSITORY+'/environments/'+a.environmentName,v=api('GET',base,undefined,ports),p=api('GET',base+'/deployment-branch-policies',undefined,ports);if(v.name!==a.environmentName||v.deployment_branch_policy?.protected_branches!==false||v.deployment_branch_policy?.custom_branch_policies!==true||p.total_count!==1||p.branch_policies?.length!==1||p.branch_policies[0].name!=='nm-ios16-'+a.operationId||p.branch_policies[0].type!=='tag')P.fail();return true;}
function verifySecret(a,present,ports={}){const v=api('GET','/repos/'+P.REPOSITORY+'/environments/'+a.environmentName+'/secrets?per_page=100',undefined,ports);if(v.total_count!==(present?1:0)||v.secrets?.length!==(present?1:0)||present&&v.secrets[0].name!=='NM_CI_AES_KEY')P.fail();return true;}
module.exports={GH,cli,api,placeAndDispatch,deleteKey,sourceBytes,preflight,createCipherRelease,verifyEnvironment,verifySecret};
