'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const BUILD_MS=7200000,RETURN_MS=180000;
function fail(){throw Error('PROTECTED_CI_BUILD_REFUSED');}
function primitiveContext(e,args=process.execArgv){if(!Array.isArray(args)||args.length||['NODE_OPTIONS','NODE_DEBUG','NODE_DEBUG_NATIVE','DEBUG'].some(k=>e[k])||e.GITHUB_REPOSITORY!=='rungerunge/loyalino-test'||e.GITHUB_ACTOR!=='rungerunge'||e.GITHUB_EVENT_NAME!=='workflow_dispatch'||e.GITHUB_RUN_ATTEMPT!=='1'||e.GITHUB_SHA!==e.NM_WORKFLOW_SHA||e.GITHUB_WORKFLOW_SHA!==e.NM_WORKFLOW_SHA||e.RUNNER_OS!=='macOS'||e.RUNNER_ARCH!=='ARM64'||e.ImageOS!=='macos26'||e.ImageVersion!=='20260907.0351.1'||e.EXPO_TOKEN||e.EAS_TOKEN||!(/^[0-9a-f]{64}$/).test(e.NM_SOURCE_REVIEW_SHA)||!(/^[0-9a-f]{40}$/).test(e.NM_WORKFLOW_SHA)||typeof e.NM_CI_AES_KEY!=='string'||typeof e.RUNNER_TEMP!=='string'||!path.isAbsolute(e.RUNNER_TEMP))fail();}
function modules(root,e){const raw=fs.readFileSync(path.join(root,'source-review.json'));if(crypto.createHash('sha256').update(raw).digest('hex')!==e.NM_SOURCE_REVIEW_SHA)fail();const review=JSON.parse(raw),row=review.files.find(x=>x.file==='bootstrap.cjs');if(!row||crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'bootstrap.cjs'))).digest('hex')!==row.sha256)fail();const B=require('./bootstrap.cjs'),held=B.hold(root,e.NM_SOURCE_REVIEW_SHA);return{held,P:require('./policy.cjs'),E:require('./envelope.cjs'),I:require('./payload.cjs'),J:require('./job.cjs'),G:require('./github-release.cjs'),C:require('./private-capture.cjs'),Probe:require('./macos-probe.cjs')};}
async function toolchain(m,e,run,cwd){const env=m.C.environment(e);for(const [name,file,args]of m.Probe.TOOLS){const r=await run(file||process.execPath,args,{cwd,env,timeoutMs:30000}),v=m.Probe.projection(name,r),want=m.P.TOOLCHAIN[name];if(!v.observed||v.version!==want||name==='xcode'&&v.build!==m.P.TOOLCHAIN.xcodeBuild)fail();}const ps=await run('/usr/bin/env',['pwsh','-NoLogo','-NoProfile','-NonInteractive','-Command','$PSVersionTable.PSVersion.ToString()'],{cwd,env,timeoutMs:30000});if(ps.status!==0||ps.error||ps.signal||!Buffer.from(ps.stdout.toString('utf8')).equals(ps.stdout)||ps.stdout.toString('utf8').trim()!=='7.6.5')fail();return m.P.TOOLCHAIN_SHA;}
function context(a,direction){return{operationId:a.operationId,direction,workflowCommit:a.workflowCommit,sourceReviewSha256:a.sourceReviewSha256,nativeSource:a.nativeSource,backendSource:a.backendSource,version:16};}
async function perform(input,key,m,e,ports){const io=ports.fs||fs,paths=ports.path||path,now=ports.now,check=()=>m.held.check(),logs=[];const a=input.approval;m.P.approval(a,now());m.P.runtime({repository:e.GITHUB_REPOSITORY,actor:e.GITHUB_ACTOR,event:e.GITHUB_EVENT_NAME,workflowCommit:e.GITHUB_SHA,runId:Number(e.GITHUB_RUN_ID),runAttempt:Number(e.GITHUB_RUN_ATTEMPT),runnerLabel:m.P.RUNNER,runnerOs:e.RUNNER_OS,environmentName:e.NM_ENVIRONMENT_NAME,xcodeVersion:m.P.TOOLCHAIN.xcode,iosSdkVersion:m.P.TOOLCHAIN.iosSdk,expoTokenPresent:!!e.EXPO_TOKEN,paidRunner:false,cache:false,actionsArtifacts:false,packages:false,lfs:false},a);
 const v=m.I.validate(input,a);if(v.runtimeLockSha256!==m.P.sha(io.readFileSync(paths.join(__dirname,'runtime-package-lock.json'))))fail();
 const admitted=now(),deadline=admitted+BUILD_MS;const claim=Buffer.from(JSON.stringify(m.E.seal(Buffer.from(JSON.stringify({operationId:a.operationId,runId:Number(e.GITHUB_RUN_ID),workflowCommit:a.workflowCommit,admittedAt:new Date(admitted).toISOString(),inputCipherSha256:e.NM_INPUT_CIPHER_SHA})),key,context(a,'CLAIM'),crypto.randomBytes(12))));check();await ports.claim(claim);check();m.P.approval(a,now());
 const root=ports.directory(a.operationId),project=paths.join(root,'project'),artifact=paths.join(root,'artifacts');
 const run=async(file,args,extra={},ms=BUILD_MS)=>{check();if(now()>=deadline)fail();const r=await ports.run(file,args,{cwd:root,env:m.C.environment(e,extra),timeoutMs:Math.min(ms,deadline-now())});logs.push({stage:file===process.execPath?'BUILD':'AUDIT',status:r.status,error:r.error,signal:r.signal,stdout:r.stdout.toString('base64'),stderr:r.stderr.toString('base64')});check();if(now()>=deadline||r.status!==0||r.error||r.signal)fail();return r;};
 try{
  io.mkdirSync(project,{mode:0o700});io.mkdirSync(artifact,{mode:0o700});for(const r of v.rows){const dest=paths.join(project,r.path);if(!dest.startsWith(project+paths.sep))fail();io.mkdirSync(paths.dirname(dest),{recursive:true,mode:0o700});io.writeFileSync(dest,r.bytes,{flag:'wx',mode:r.mode==='100755'?0o700:0o600});}
  await toolchain(m,e,ports.run,root);check();m.P.approval(a,now());
  const runtime=paths.join(root,'runtime');io.mkdirSync(runtime,{mode:0o700});for(const [src,dest]of [['runtime-package.json','package.json'],['runtime-package-lock.json','package-lock.json']])io.writeFileSync(paths.join(runtime,dest),io.readFileSync(paths.join(__dirname,src)),{flag:'wx',mode:0o600});for(const name of ['user.npmrc','global.npmrc'])io.writeFileSync(paths.join(runtime,name),'',{flag:'wx',mode:0o600});
  const installed=await ports.run('/usr/bin/env',['npm','ci','--ignore-scripts','--no-audit','--no-fund','--registry=https://registry.npmjs.org','--userconfig='+paths.join(runtime,'user.npmrc'),'--globalconfig='+paths.join(runtime,'global.npmrc')],{cwd:runtime,env:m.C.environment(e,{PATH:paths.dirname(process.execPath)+':'+e.PATH,npm_config_cache:paths.join(root,'npm-cache')}),timeoutMs:Math.min(600000,deadline-now())});logs.push({stage:'BUILD',status:installed.status,error:installed.error,signal:installed.signal,stdout:installed.stdout.toString('base64'),stderr:installed.stderr.toString('base64')});check();if(installed.status!==0||installed.error||installed.signal||now()>=deadline)fail();m.P.approval(a,now());
  await run('/usr/bin/tar',['-czf',paths.join(root,'project.tgz'),'-C',project,'.'],{},60000);
  const buildJob=(ports.load||require)(paths.join(runtime,'node_modules/@expo/eas-build-job')),material={p12:Buffer.from(v.material.p12,'base64'),cms:Buffer.from(v.material.cms,'base64'),password:v.material.password};
  let rendered;try{rendered=m.J.render(material,paths.join(root,'project.tgz'),v.ownerId,v.publicEnv,root,buildJob.sanitizeBuildJob);}finally{material.p12.fill(0);material.cms.fill(0);material.password=null;}
  const jobRaw=Buffer.from(JSON.stringify(rendered)),jobSha256=m.P.sha(jobRaw),jobHmac=crypto.createHmac('sha256',key).update('NM_CI16_JOB\0').update(jobRaw).digest('hex'),startedAt=new Date(now()).toISOString();m.P.approval(a,Date.parse(startedAt));check();
  await run(process.execPath,[paths.join(runtime,'node_modules/eas-cli-local-build-plugin/bin/run')],{__API_SERVER_URL:'https://api.expo.dev',EAS_LOCAL_BUILD_PLUGIN_INPUT:jobRaw.toString('base64'),EAS_LOCAL_BUILD_WORKINGDIR:paths.join(root,'work'),EAS_LOCAL_BUILD_ARTIFACTS_DIR:artifact,EAS_LOCAL_BUILD_LOGGER_LEVEL:'info'});jobRaw.fill(0);rendered.job.secrets=null;
  const files=io.readdirSync(artifact);if(files.length!==1||!files[0].endsWith('.ipa'))fail();const ipa=io.readFileSync(paths.join(artifact,files[0]));if(ipa.length<1000000||ipa.length>200*1024*1024)fail();
  const audit=JSON.parse((await run('/usr/bin/env',['python3',paths.join(__dirname,'native-audit.py'),paths.join(artifact,files[0])],{},120000)).stdout.toString('utf8'));
  if(audit.ipaSha256!==m.P.sha(ipa)||audit.ipaBytes!==ipa.length||audit.independentSignedResourcesVerified!==true||audit.hermesSourceAssociationVerified!==true||audit.privacyManifestVerified!==true)fail();
  const cmsInput={...audit.cmsEvidence,certificateSerialSha256:a.certificateSerialSha256,profileUuidSha256:a.profileUuidSha256,referenceProfile:v.material.cms};delete cmsInput.codeDirectories;
  const cms=await ports.cms(cmsInput,root,deadline-now());logs.push({stage:'AUDIT',status:cms.status,error:cms.error,signal:cms.signal,stdout:cms.stdout.toString('base64'),stderr:cms.stderr.toString('base64')});if(cms.status!==0||cms.error||cms.signal||cms.stderr.length||now()>=deadline)fail();const cv=JSON.parse(cms.stdout.toString('utf8'));if(!m.P.exact(cv,['embeddedProfileExact','profileCmsVerified','executableCmsVerified','expectedSignerVerified'])||Object.values(cv).some(v=>v!==true))fail();delete audit.cmsEvidence;
  for(const r of v.rows){const b=io.readFileSync(paths.join(project,r.path));if(!b.equals(r.bytes))fail();}
  await toolchain(m,e,ports.run,root);check();if(now()>=deadline)fail();
  return{kind:'ROOT_CI16_PRIVATE_LOCAL_BUILD_OUTPUT',operationId:a.operationId,runId:Number(e.GITHUB_RUN_ID),runAttempt:1,workflowCommit:a.workflowCommit,admittedAt:new Date(admitted).toISOString(),startedAt,finishedAt:new Date(now()).toISOString(),toolchainSha256:m.P.TOOLCHAIN_SHA,powershellVersion:'7.6.5',jobRootDirectory:root,jobSha256,jobHmac,ipaBase64:ipa.toString('base64'),audit,logs,sourceVerified:true,cmsVerified:true,localPlugin:true,easCloudBuildId:null,easFinishedVerified:false,physicalVerified:false,testFlightSubmitted:false};
 }catch{const x=Error('PROTECTED_BUILD_REFUSED');x.privateOutput={kind:'ROOT_CI16_PRIVATE_BUILD_FAILURE',operationId:a.operationId,runId:Number(e.GITHUB_RUN_ID),failedAt:new Date(now()).toISOString(),logs,detailsSuppressedPublic:true};throw x;}
 finally{v.material.password=null;v.material.p12=null;v.material.cms=null;ports.cleanup(root);}
}
async function main(args=[],ports={}){
 if(args.length===0)return{preparedOnly:true,credentials:0,network:0,builds:0};if(args.length!==1||args[0]!=='--build')fail();const e=ports.env||process.env;primitiveContext(e);const m=modules(__dirname,e),key=Buffer.from(e.NM_CI_AES_KEY,'base64');if(key.length!==32||key.toString('base64')!==e.NM_CI_AES_KEY)fail();let a=null,output,bad=false;
 try{const header={operationId:e.NM_OPERATION_ID,workflowCommit:e.NM_WORKFLOW_SHA,sourceReviewSha256:e.NM_SOURCE_REVIEW_SHA,nativeSource:m.P.SOURCE,backendSource:m.P.BACKEND_SOURCE,version:16},pre={...header};if(!m.P.UUID.test(header.operationId))fail();const cipher=await m.G.download(pre,Number(e.NM_RELEASE_ID),Number(e.NM_INPUT_ASSET_ID),e.NM_INPUT_CIPHER_SHA,Number(e.NM_INPUT_CIPHER_BYTES),e.GITHUB_TOKEN),plain=m.E.open(JSON.parse(cipher.toString('utf8')),key,{...header,direction:'INPUT'});let input;try{input=JSON.parse(plain.toString('utf8'));}finally{plain.fill(0);}a=input.approval;
  try{output=await perform(input,key,m,e,{now:Date.now,claim:c=>m.G.put(a,Number(e.NM_RELEASE_ID),'claim',c,e.GITHUB_TOKEN),run:m.C.run,directory:id=>{const base=fs.realpathSync(e.RUNNER_TEMP);const dir=fs.mkdtempSync(path.join(base,'nm-ci16-'+id+'-'));fs.chmodSync(dir,0o700);return dir;},cms:(v,cwd,timeoutMs)=>new Promise(resolve=>{const cp=require('node:child_process'),r=cp.spawnSync('/usr/bin/env',['pwsh','-NoLogo','-NoProfile','-NonInteractive','-File',path.join(__dirname,'ipa-cms-check.ps1')],{input:JSON.stringify(v),cwd,env:m.C.environment(e),timeout:Math.min(timeoutMs,60000),maxBuffer:65536,encoding:null,shell:false});resolve({status:r.status,error:!!r.error,signal:r.signal,stdout:r.stdout||Buffer.alloc(0),stderr:r.stderr||Buffer.alloc(0)});}),cleanup:dir=>{const base=fs.realpathSync(e.RUNNER_TEMP);if(!path.resolve(dir).startsWith(base+path.sep+'nm-ci16-'+a.operationId+'-')||fs.realpathSync(dir)!==path.resolve(dir))fail();fs.rmSync(dir,{recursive:true,force:false});}});}catch(error){bad=true;output=error.privateOutput;if(!output)fail();}
  const returnDeadline=Date.now()+RETURN_MS,encoded=Buffer.from(JSON.stringify(output));try{const result=await m.G.put(a,Number(e.NM_RELEASE_ID),'output',Buffer.from(JSON.stringify(m.E.seal(encoded,key,context(a,'OUTPUT'),crypto.randomBytes(12)))),e.GITHUB_TOKEN);m.held.check();if(Date.now()>=returnDeadline)fail();return{kind:'ROOT_CI16_CIPHER_RETURN',operationId:a.operationId,runId:Number(e.GITHUB_RUN_ID),buildSucceeded:!bad,...result,rawLogsPublic:false,plainIpaPublic:false,sourceSignersPublic:false,easFinishedVerified:false};}finally{encoded.fill(0);}
 }finally{key.fill(0);}
}
module.exports={BUILD_MS,RETURN_MS,primitiveContext,toolchain,context,perform,main};
if(require.main===module)main(process.argv.slice(2)).then(v=>{process.stdout.write(JSON.stringify(v)+'\n');if(v.buildSucceeded===false)process.exitCode=1;}).catch(()=>{process.stdout.write('{"protectedBuild":false,"detailsSuppressed":true}\n');process.exitCode=1;});
