'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
function fail(){throw Error('PROTECTED_SOURCE_REFUSED');}
function read(file,max=1048576){if(typeof file!=='string'||!path.isAbsolute(file)||!Number.isSafeInteger(max)||max<1)fail();const s=fs.lstatSync(file),real=fs.realpathSync.native(file);if(!s.isFile()||s.isSymbolicLink()||s.nlink!==1||s.size<1||s.size>max||path.normalize(real).toLowerCase()!==path.normalize(file).toLowerCase())fail();const fd=fs.openSync(file,fs.constants.O_RDONLY);try{const t=fs.fstatSync(fd);if(!same(s,t))fail();const b=Buffer.alloc(s.size);let n=0;while(n<b.length){const count=fs.readSync(fd,b,n,b.length-n,n);if(count<1)fail();n+=count;}const extra=Buffer.alloc(1);if(fs.readSync(fd,extra,0,1,n)!==0||!same(s,fs.fstatSync(fd))||!same(s,fs.lstatSync(file))||fs.realpathSync.native(file)!==real)fail();return b;}finally{fs.closeSync(fd);}}
function same(a,b){return ['dev','ino','nlink','mode','size','mtimeMs','ctimeMs'].every(k=>a[k]===b[k]);}
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function hold(rows,root){if(!Array.isArray(rows)||rows.length<1||rows.length>1000)fail();const out=[];for(const r of rows){if(!r||Object.keys(r).sort().join(',')!=='bytes,file,sha256'||!Number.isSafeInteger(r.bytes)||r.bytes<1||!(/^[a-f0-9]{64}$/).test(r.sha256))fail();const file=path.isAbsolute(r.file)?r.file:path.join(root,r.file);if(!path.isAbsolute(r.file)&&!(/^[A-Za-z0-9_.-]+$/).test(r.file))fail();const b=read(file,r.bytes);if(b.length!==r.bytes||sha(b)!==r.sha256)fail();out.push({file,bytes:r.bytes,sha256:r.sha256});}return out;}
function check(rows){hold(rows,'');}
function startup(env,args){if(args.length||['NODE_OPTIONS','NODE_DEBUG','NODE_DEBUG_NATIVE','DEBUG','RUST_LOG'].some(k=>env[k]!==undefined&&env[k]!==''))fail();for(const [k,v]of Object.entries(env))if(v&&(/proxy/i.test(k)||/^(EXPO_API_URL|EXPO_STAGING|EAS_LOCAL_BUILD|EAS_BUILD|NODE_EXTRA_CA_CERTS|NODE_TLS_REJECT_UNAUTHORIZED|SSL_CERT_FILE|SSL_CERT_DIR)/.test(k)))fail();}
module.exports={read,same,sha,hold,check,startup};
