'use strict';
const crypto=require('node:crypto');
const SOURCE='a59e987d45d59ae6e6cdc53620c1640495cd4626',PROJECT='adf6c486-4d81-4e19-b6b7-25e5b4ca1064',ACCOUNT='okayscales-team',BUNDLE='dk.nevermonday.app',TEAM='XNPLDX9MHP',SDK_VERSION='24.8.0';
const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/,HEX=/^[a-f0-9]{64}$/;
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function fail(){throw Error('Signing metadata read-only guard rejected');}
function exact(v,k){return !!v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).sort().join('|')===k.slice().sort().join('|');}
function opaque(v){if(typeof v!=='string'||!/^[A-Za-z0-9_-]{1,100}$/.test(v))fail();return v;}
function date(v){if(typeof v!=='string'||!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d{1,3})?Z$/.test(v))fail();const n=Date.parse(v);if(!Number.isFinite(n)||new Date(n).toISOString().slice(0,19)!==v.slice(0,19))fail();return n;}
function canonicalTime(v,now,maxAge){const n=date(v);if(new Date(n).toISOString()!==v||n>now||now-n>maxAge)fail();return n;}
const KEYS=['schemaVersion','authorized','rootReviewed','requestId','source','build','project','account','bundle','team','sdkVersion','entrySha256','preparationSha256','ownerAccountSha256','referenceSigningProofSha256','certificateSerialSha256','profileUuidSha256','approvedAt','expiresAt','noAutomaticRetry'];
function approval(a,id,entry,receipt,now){if(!exact(a,KEYS)||a.schemaVersion!==1||a.authorized!==true||a.rootReviewed!==true||a.requestId!==id||!UUID.test(id)||a.source!==SOURCE||a.build!==15||a.project!==PROJECT||a.account!==ACCOUNT||a.bundle!==BUNDLE||a.team!==TEAM||a.sdkVersion!==SDK_VERSION||a.entrySha256!==sha(entry)||a.preparationSha256!==sha(receipt)||a.noAutomaticRetry!==true||['ownerAccountSha256','referenceSigningProofSha256','certificateSerialSha256','profileUuidSha256'].some(k=>!HEX.test(a[k]||'')||/^0+$/.test(a[k])))fail();const at=canonicalTime(a.approvedAt,now,600000),end=canonicalTime(a.expiresAt,Date.parse(a.expiresAt),0);if(end<=now||end<=at||end-at>600000)fail();return a;}
function team(v,expectedId){if(!exact(v,['id','appleTeamIdentifier'])||v.appleTeamIdentifier!==TEAM||expectedId!==undefined&&v.id!==expectedId)fail();return opaque(v.id);}
function owner(v,a){if(!exact(v,['id','name'])||v.name!==ACCOUNT||sha(opaque(v.id))!==a.ownerAccountSha256)fail();return v.id;}
function discover(data,a){if(!exact(data,['app'])||!exact(data.app,['byId']))fail();const app=data.app.byId;if(!exact(app,['id','ownerAccount','iosAppCredentials'])||app.id!==PROJECT)fail();const ownerId=owner(app.ownerAccount,a),rows=app.iosAppCredentials;if(!Array.isArray(rows)||rows.length<1||rows.length>8)fail();const ids=new Set(),matching=[];
 for(const v of rows){if(!exact(v,['id','appleTeam','appleAppIdentifier'])||!exact(v.appleAppIdentifier,['id','bundleIdentifier'])||ids.has(opaque(v.id)))fail();ids.add(v.id);opaque(v.appleAppIdentifier.id);if(v.appleAppIdentifier.bundleIdentifier===BUNDLE){team(v.appleTeam);matching.push(v);}}
 if(matching.length!==1)fail();const v=matching[0];return {ownerId,credentialId:v.id,identifierId:v.appleAppIdentifier.id,teamId:v.appleTeam.id};
}
function assess(data,a,selected,now){if(!exact(data,['app'])||!exact(data.app,['byId']))fail();const app=data.app.byId;if(!exact(app,['id','ownerAccount','iosAppCredentials'])||app.id!==PROJECT||owner(app.ownerAccount,a)!==selected.ownerId||!Array.isArray(app.iosAppCredentials)||app.iosAppCredentials.length!==1)fail();const v=app.iosAppCredentials[0];if(!exact(v,['id','appleTeam','appleAppIdentifier','iosAppBuildCredentialsList'])||v.id!==selected.credentialId||!exact(v.appleAppIdentifier,['id','bundleIdentifier'])||v.appleAppIdentifier.id!==selected.identifierId||v.appleAppIdentifier.bundleIdentifier!==BUNDLE)fail();team(v.appleTeam,selected.teamId);const builds=v.iosAppBuildCredentialsList;if(!Array.isArray(builds)||builds.length!==1)fail();const b=builds[0];if(!exact(b,['id','iosDistributionType','distributionCertificate','provisioningProfile'])||b.iosDistributionType!=='APP_STORE')fail();opaque(b.id);const c=b.distributionCertificate,p=b.provisioningProfile;
 if(!exact(c,['id','serialNumber','validityNotBefore','validityNotAfter','updatedAt','appleTeam','account'])||!exact(p,['id','appleUUID','expiration','status','updatedAt','appleTeam','account','appleAppIdentifier']))fail();opaque(c.id);opaque(p.id);team(c.appleTeam,selected.teamId);team(p.appleTeam,selected.teamId);if(owner(c.account,a)!==selected.ownerId||owner(p.account,a)!==selected.ownerId||!exact(p.appleAppIdentifier,['id','bundleIdentifier'])||p.appleAppIdentifier.id!==selected.identifierId||p.appleAppIdentifier.bundleIdentifier!==BUNDLE||(p.status!=='ACTIVE'&&p.status!=='active'))fail();
 if(typeof c.serialNumber!=='string'||!/^[a-fA-F0-9]{1,64}$/.test(c.serialNumber)||typeof p.appleUUID!=='string'||!/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/.test(p.appleUUID))fail();const certificateSerialSha256=sha(c.serialNumber.toUpperCase()),profileUuidSha256=sha(p.appleUUID.toUpperCase());if(certificateSerialSha256!==a.certificateSerialSha256||profileUuidSha256!==a.profileUuidSha256)fail();const start=date(c.validityNotBefore),end=date(c.validityNotAfter),expires=date(p.expiration);if(start>now||end<=now||start>=end||expires<=now||date(c.updatedAt)>now||date(p.updatedAt)>now)fail();
 return {schemaVersion:1,kind:'IOS15_EXISTING_EAS_SIGNING_METADATA_OBSERVATION',verified:true,metadataOnly:true,actualObservation:true,source:SOURCE,build:15,project:PROJECT,account:ACCOUNT,bundle:BUNDLE,team:TEAM,sdkVersion:SDK_VERSION,collectedAt:new Date(now).toISOString(),ownerAccountSha256:a.ownerAccountSha256,referenceSigningProofSha256:a.referenceSigningProofSha256,certificateSerialSha256,profileUuidSha256,certificateIdSha256:sha(c.id),profileIdSha256:sha(p.id),buildCredentialIdSha256:sha(b.id),certificateNotBefore:new Date(start).toISOString(),certificateNotAfter:new Date(end).toISOString(),profileExpiration:new Date(expires).toISOString(),storedProfileStatus:'ACTIVE',storedValidityVerified:true,referenceSerialAndProfileUuidMatch:true,currentAppleRevocationVerified:false,embeddedProfileCertificateVerified:false,profileEntitlementsVerified:false,actual15CmsVerified:false,productionSigningReady:false,queryCount:2,networkOnly:true,noSdkRetry:true,cloudMutations:0,authWrites:0,credentialsPrinted:false,noAutomaticRetry:true};
}
module.exports={SOURCE,PROJECT,ACCOUNT,BUNDLE,TEAM,SDK_VERSION,UUID,HEX,sha,fail,exact,opaque,date,canonicalTime,KEYS,approval,team,owner,discover,assess};
