'use strict';
// Per-operation immutable byte attestation plus genuinely fresh mutable authority.
const crypto=require('node:crypto'),path=require('node:path');
const ROOT=__dirname,COUNT=57,SHA=/^[a-f0-9]{40}$/,sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const PROBE='C:/Users/runge/.nevermonday-secrets/ios16-protected-github-macos-source-20261006/macos-toolchain-probe.yml';
const OLD_WORKFLOW='C:/Users/runge/.nevermonday-secrets/ios16-protected-github-macos-signature-capacity-20261006/protected-ios16.yml';
const WORKFLOWS=['.github/workflows/nm-ios16-toolchain-probe.yml','.github/workflows/nm-protected-ios16.yml','.github/workflows/nm-protected-ios17.yml'];
function fail(code){throw Error(code);}
function blob(b){return crypto.createHash('sha1').update(Buffer.from('blob '+b.length+'\0')).update(b).digest('hex');}
function create(a,review,ports,GH,H,P,onStage=()=>{}){
 if(!a||!P.UUID.test(a.operationId)||!SHA.test(a.workflowCommit)||!P.SHA.test(a.sourceReviewSha256)||!review||review.files?.length!==COUNT||new Set(review.files.map(r=>r.file)).size!==COUNT||typeof ports.check!=='function'||typeof ports.now!=='function')fail('IMMUTABLE_BINDING_REFUSED');
 const binding=Object.freeze({operationId:a.operationId,workflowCommit:a.workflowCommit,sourceReviewSha256:a.sourceReviewSha256,filesSha256:sha(JSON.stringify(review.files))});let attestation=null,bodyCalls=0,authorityCalls=0;
 const api=endpoint=>GH.api('GET',endpoint,undefined,ports),repo='/repos/'+P.REPOSITORY;
 const same=()=>{ports.check();if(a.operationId!==binding.operationId||a.workflowCommit!==binding.workflowCommit||a.sourceReviewSha256!==binding.sourceReviewSha256||sha(JSON.stringify(review.files))!==binding.filesSha256)fail('IMMUTABLE_BINDING_REFUSED');};
 function commit(expectedTree){onStage('COMMIT_AUTHORITY');const v=api(repo+'/git/commits/'+binding.workflowCommit);if(v.sha!==binding.workflowCommit||!SHA.test(v.tree?.sha)||expectedTree&&v.tree.sha!==expectedTree)fail('IMMUTABLE_COMMIT_REFUSED');return v.tree.sha;}
 function initialize(){same();const treeSha=commit();onStage('IMMUTABLE_TREE');const tree=api(repo+'/git/trees/'+treeSha+'?recursive=1');if(tree.sha!==treeSha||tree.truncated!==false||!Array.isArray(tree.tree)||tree.tree.length<COUNT||tree.tree.length>1000||new Set(tree.tree.map(r=>r.path)).size!==tree.tree.length)fail('IMMUTABLE_TREE_REFUSED');const index=new Map();for(const r of tree.tree){if(typeof r.path!=='string'||r.path.length<1||r.path.length>512||r.path.startsWith('/')||r.path.split('/').some(s=>!s||s==='.'||s==='..')||/[\\\x00-\x1f\x7f]/.test(r.path)||!SHA.test(r.sha)||!['blob','tree','commit'].includes(r.type))fail('IMMUTABLE_TREE_REFUSED');index.set(r.path,r);}
  const reviewRaw=H.read(path.join(ROOT,'source-review.json'),2000000);if(sha(reviewRaw)!==binding.sourceReviewSha256||JSON.stringify(JSON.parse(reviewRaw).files)!==JSON.stringify(review.files))fail('IMMUTABLE_BODY_REFUSED');const wanted=review.files.map(r=>({remote:'.github/protected-ios17/'+r.file,local:path.join(ROOT,r.file),bytes:r.bytes,sha256:r.sha256}));const workflow=review.files.find(r=>r.file==='protected-ios17.yml');if(!workflow)fail('IMMUTABLE_BODY_REFUSED');wanted.push({remote:'.github/protected-ios17/source-review.json',local:path.join(ROOT,'source-review.json'),bytes:reviewRaw.length,sha256:binding.sourceReviewSha256},{remote:'.github/workflows/nm-protected-ios17.yml',local:path.join(ROOT,'protected-ios17.yml'),bytes:workflow.bytes,sha256:workflow.sha256});for(const [remote,local]of [[WORKFLOWS[0],PROBE],[WORKFLOWS[1],OLD_WORKFLOW]]){const b=H.read(local,2000000);wanted.push({remote,local,bytes:b.length,sha256:sha(b)});}
  const verified=[];onStage('IMMUTABLE_SOURCE');for(const r of wanted){same();const local=H.read(r.local,r.bytes),git=index.get(r.remote);if(local.length!==r.bytes||sha(local)!==r.sha256||git?.type!=='blob'||git.mode!=='100644'||git.sha!==blob(local))fail('IMMUTABLE_TREE_REFUSED');const b=GH.sourceBytes(r.remote,binding.workflowCommit,ports);bodyCalls++;if(b.length!==r.bytes||sha(b)!==r.sha256||blob(b)!==git.sha)fail('IMMUTABLE_BODY_REFUSED');verified.push({path:r.remote,bytes:r.bytes,sha256:r.sha256,gitBlob:git.sha});}same();attestation=Object.freeze({...binding,treeSha,sourceBodiesVerified:wanted.length,canonicalBlobsSha256:sha(JSON.stringify(verified)),providerBodiesVerified:true,apiResponsesCached:false});}
 function preflight(requireTag=false){same();if(!attestation)initialize();same();onStage('MUTABLE_REPOSITORY');const observedAt=new Date(ports.now()).toISOString(),u=api('/user'),v=api(repo),p=api(repo+'/actions/permissions'),c=api(repo+'/collaborators?per_page=100'),invitations=api(repo+'/invitations?per_page=100'),ref=api(repo+'/git/ref/'+(requireTag?'tags/nm-ios17-'+a.operationId:'heads/main')),workflows=api(repo+'/actions/workflows?per_page=100');authorityCalls++;if(u.login!==P.ACTOR||v.full_name!==P.REPOSITORY||v.private!==false||v.archived!==false||v.disabled!==false||v.permissions?.admin!==true||p.enabled!==true||p.allowed_actions!=='all'||!Array.isArray(c)||c.length!==1||c[0].login!==P.ACTOR||c[0].permissions?.admin!==true||!Array.isArray(invitations)||invitations.length||ref.object?.type!=='commit'||ref.object.sha!==binding.workflowCommit||workflows.total_count!==WORKFLOWS.length||workflows.workflows?.length!==WORKFLOWS.length||workflows.workflows.map(r=>r.path).sort().join('|')!==WORKFLOWS.join('|'))fail('MUTABLE_AUTHORITY_REFUSED');if(requireTag){const main=api(repo+'/git/ref/heads/main');if(main.object?.type!=='commit'||main.object.sha!==binding.workflowCommit)fail('MUTABLE_AUTHORITY_REFUSED');}commit(attestation.treeSha);same();const current={repository:P.REPOSITORY,public:true,archived:false,disabled:false,admin:true,actionsEnabled:true,unexpectedWriters:0,workflowsReviewed:true,refSha:binding.workflowCommit,observedAt};P.repository(current,ports.now());return current;}
 function runAbsent(){same();const v=api(repo+'/actions/workflows/nm-protected-ios17.yml/runs?event=workflow_dispatch&head_sha='+binding.workflowCommit+'&per_page=100');if(!Number.isSafeInteger(v.total_count)||v.total_count<0||v.total_count>100||!Array.isArray(v.workflow_runs)||v.workflow_runs.length!==v.total_count)fail('CURRENT_RUN_REFUSED');const seen=new Set();for(const r of v.workflow_runs){if(!Number.isSafeInteger(r.id)||r.id<1||seen.has(r.id)||r.head_sha!==binding.workflowCommit||r.event!=='workflow_dispatch'||typeof r.display_title!=='string')fail('CURRENT_RUN_REFUSED');seen.add(r.id);if(r.head_branch==='nm-ios17-'+binding.operationId||r.display_title==='Protected iOS17 '+binding.operationId)fail('CURRENT_RUN_EXISTS');}same();return true;}
 return Object.freeze({preflight,runAbsent,inspect:()=>attestation?Object.freeze({...attestation,bodyCalls,authorityCalls}):null});
}
module.exports={ROOT,COUNT,WORKFLOWS,sha,blob,create};
