'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),cp=require('node:child_process');
const ROOT=__dirname,PRIVATE=path.join(ROOT,'protected');
const PYTHON='C:/Users/runge/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',PWSH='C:/Users/runge/.cache/codex-runtimes/codex-primary-runtime/dependencies/native/powershell/pwsh.exe';
function fail(){throw Error('ROOT_CI17_RECEIVE_REFUSED');}
async function execute(id,runId){if(process.execArgv.length||!(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/).test(id)||!Number.isSafeInteger(runId)||runId<1)fail();const dir=path.join(PRIVATE,id),a=JSON.parse(fs.readFileSync(path.join(dir,'approval.json'))),reviewRaw=fs.readFileSync(path.join(ROOT,'source-review.json')),hash=b=>crypto.createHash('sha256').update(b).digest('hex');if(hash(reviewRaw)!==a.sourceReviewSha256)fail();const row=JSON.parse(reviewRaw).files.find(x=>x.file==='bootstrap.cjs');if(!row||hash(fs.readFileSync(path.join(ROOT,'bootstrap.cjs')))!==row.sha256)fail();const B=require('./bootstrap.cjs'),held=B.hold(ROOT,a.sourceReviewSha256),P=require('./policy.cjs'),H=require('./held-source.cjs'),G=require('./github-release.cjs'),GH=require('./root-github.cjs'),R=require('./receiver.cjs'),Env=require('./root-export.cjs');H.startup(process.env,[]);const deps=H.hold(held.v.sourceDependencies,ROOT),history=require('./failed-operation-9c.cjs').holdAll(H.read),check=()=>{held.check();H.check(deps);require('./failed-operation-9c.cjs').same(history,H.read);};check();const request=JSON.parse(H.read(path.join(dir,'return-request.json'),32000));if(!P.exact(request,['releaseId','outputAssetId','outputCipherSha256','outputCipherBytes'])||!Number.isSafeInteger(request.releaseId)||!Number.isSafeInteger(request.outputAssetId)||!P.SHA.test(request.outputCipherSha256)||!Number.isSafeInteger(request.outputCipherBytes)||request.outputCipherBytes>G.MAX_CIPHER)fail();
 const actual=GH.api('GET','/repos/'+P.REPOSITORY+'/actions/runs/'+runId,undefined,{check}),jobs=GH.api('GET','/repos/'+P.REPOSITORY+'/actions/runs/'+runId+'/jobs?filter=all',undefined,{check});check();if(actual.repository?.full_name!==P.REPOSITORY||actual.actor?.login!==P.ACTOR||actual.event!=='workflow_dispatch'||actual.run_attempt!==1||actual.head_sha!==a.workflowCommit||actual.path!=='.github/workflows/nm-protected-ios17.yml'||actual.status!=='completed'||actual.conclusion!=='success'||jobs.total_count!==1||jobs.jobs?.length!==1)fail();const job=jobs.jobs[0];if(job.run_id!==runId||job.run_attempt!==1||job.status!=='completed'||job.conclusion!=='success'||!job.labels?.includes('macos-26')||job.labels.some(x=>/large|xlarge|self-hosted/.test(x)))fail();
 const actualRun={repository:P.REPOSITORY,actor:P.ACTOR,event:actual.event,runId,runAttempt:1,headSha:actual.head_sha,workflowPath:actual.path,status:actual.status,conclusion:actual.conclusion,jobStartedAt:new Date(job.started_at).toISOString(),jobFinishedAt:new Date(job.completed_at).toISOString(),observedAt:new Date().toISOString()};
 const meta=G.release(GH.api('GET','/repos/'+P.REPOSITORY+'/releases/'+request.releaseId,undefined,{check}),a,request.releaseId),asset=meta.assets.filter(x=>x.id===request.outputAssetId&&x.name==='output-'+id+'.nmae'&&x.state==='uploaded'&&x.size===request.outputCipherBytes);if(asset.length!==1||asset[0].digest&&asset[0].digest!=='sha256:'+request.outputCipherSha256)fail();check();const output=await G.request('api.github.com','/repos/'+P.REPOSITORY+'/releases/assets/'+request.outputAssetId,'GET',null,null);check();if(output.length!==request.outputCipherBytes||P.sha(output)!==request.outputCipherSha256)fail();check();const input=H.read(inputFile(dir,id),G.MAX_CIPHER),key=H.read(path.join(dir,'key.bin'),32);if(key.length!==32)fail();
 const invoke=(file,args,stdin)=>{check();const r=cp.spawnSync(file,args,{input:stdin,cwd:ROOT,env:Env.rootEnvironment(process.env),shell:false,encoding:null,timeout:120000,maxBuffer:16*1024*1024,windowsHide:true});check();if(r.status!==0||r.error||r.signal||r.stderr.length)fail();return JSON.parse(r.stdout.toString('utf8'));};
 try{return await R.receive(a,input,output,key,actualRun,{now:Date.now,check,reserve:()=>fs.writeFileSync(path.join(dir,'receive-once.json'),JSON.stringify({operationId:id,runId,startedAt:new Date().toISOString()})+'\n',{flag:'wx',mode:0o600}),audit:async(ipa,material)=>{const ipaPath=path.join(dir,'ci17.ipa');fs.writeFileSync(ipaPath,ipa,{flag:'wx',mode:0o600});const signer=invoke(PWSH,['-NoLogo','-NoProfile','-NonInteractive','-File',path.join(ROOT,'signer-check.ps1')],JSON.stringify({...material,certificateSerialSha256:a.certificateSerialSha256,profileUuidSha256:a.profileUuidSha256,team:P.TEAM,bundle:P.BUNDLE}));if(signer.certificateKeyPairVerified!==true||signer.profileCmsVerified!==true||signer.profileEntitlementsVerified!==true)fail();const native=invoke(PYTHON,[path.join(ROOT,'native-audit.py'),ipaPath]),cmsInput={...native.cmsEvidence,certificateSerialSha256:a.certificateSerialSha256,profileUuidSha256:a.profileUuidSha256,referenceProfile:material.cms};delete cmsInput.codeDirectories;const cms=invoke(PWSH,['-NoLogo','-NoProfile','-NonInteractive','-File',path.join(ROOT,'ipa-cms-check.ps1')],JSON.stringify(cmsInput));if(!P.exact(cms,['embeddedProfileExact','profileCmsVerified','executableCmsVerified','expectedSignerVerified'])||Object.values(cms).some(x=>x!==true)||P.sha(H.read(ipaPath,200*1024*1024))!==P.sha(ipa))fail();delete native.cmsEvidence;const proof={kind:'ROOT_INDEPENDENT_CI17_NATIVE_AUDIT',operationId:id,runId,finishedAt:new Date().toISOString(),native,cms,existingSigner:signer,nativeUiVerified:false,physicalVerified:false,currentAppleRevocationVerified:false,easFinishedVerified:false},raw=Buffer.from(JSON.stringify(proof)+'\n');fs.writeFileSync(path.join(dir,'root-native-audit.json'),raw,{flag:'wx',mode:0o600});return{rootNativeAuditSha256:P.sha(raw),ipaSha256:P.sha(ipa),ipaBytes:ipa.length,cmsVerified:true,independentSignedResourcesVerified:native.independentSignedResourcesVerified,hermesSourceAssociationVerified:native.hermesSourceAssociationVerified,privacyManifestVerified:native.privacyManifestVerified};},record:v=>fs.writeFileSync(path.join(dir,'ci17-lineage.json'),JSON.stringify(v)+'\n',{flag:'wx',mode:0o600})});}finally{key.fill(0);}}
function main(args=[]){if(args.length===0)return Promise.resolve({preparedOnly:true,network:0,artifactReads:0});if(args.length===3&&args[0]==='--receive')return execute(args[1],Number(args[2]));fail();}
function inputFile(dir,id){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(id))throw Error('INPUT_NAME_REFUSED');return path.join(dir,'input-'+id+'.nmae');}
module.exports={inputFile,PYTHON,PWSH,execute,main};
if(require.main===module)main(process.argv.slice(2)).then(v=>process.stdout.write(JSON.stringify(v)+'\n')).catch(()=>{process.stdout.write('{"protectedReceive":false,"detailsSuppressed":true}\n');process.exitCode=1;});
