'use strict';
const https=require('node:https'),P=require('./policy.cjs');
const MAX_CIPHER=400*1024*1024;
function redirect(location){let u;try{u=new URL(location);}catch{P.fail();}if(u.protocol!=='https:'||u.hostname!=='release-assets.githubusercontent.com'||u.port||u.username||u.password||u.hash||!u.pathname.startsWith('/github-production-release-asset/')||u.href.length>12000)P.fail();return{host:u.hostname,path:u.pathname+u.search};}
function request(host,path,method,body,token,ports={}){
 const binary=method==='GET'&&path.startsWith('/repos/'+P.REPOSITORY+'/releases/assets/');
 if(!['api.github.com','uploads.github.com'].includes(host)||typeof path!=='string'||!path.startsWith('/repos/'+P.REPOSITORY+'/releases/')||!['GET','POST'].includes(method)||method==='POST'&&(host!=='uploads.github.com'||!Buffer.isBuffer(body)||body.length<1||body.length>MAX_CIPHER)||token!==null&&(typeof token!=='string'||token.length<1||/[\x00-\x20]/.test(token)))P.fail();
 const max=binary?MAX_CIPHER:1048576;
 return new Promise((resolve,reject)=>{let req,res,t,total=0,done=false;const bits=[],http=ports.https||https,timer=ports.setTimeout||setTimeout,clear=ports.clearTimeout||clearTimeout;
  const finish=(bad,result)=>{if(done)return;done=true;if(t!==undefined)clear(t);if(bad){req?.destroy();res?.destroy();reject(Error('CIPHER_RELEASE_REFUSED'));}else resolve(result);};
  const send=(h,p,second)=>{if(done)return;try{req=http.request({hostname:h,port:443,path:p,method,agent:false,rejectUnauthorized:true,headers:{'user-agent':'nm-protected-ci18',...(second?{accept:'application/octet-stream'}:{'x-github-api-version':'2022-11-28',accept:binary?'application/octet-stream':'application/vnd.github+json',...(token?{authorization:'Bearer '+token}:{}),...(body?{'content-type':'application/octet-stream','content-length':body.length}:{})})}},r=>{res=r;if(done){r.destroy();return;}if(r.statusCode===302&&binary&&!second&&typeof r.headers.location==='string'){try{const u=redirect(r.headers.location);r.resume();send(u.host,u.path,true);}catch{finish(true);}return;}if(r.headers.location!==undefined||r.statusCode!==(method==='POST'?201:200)){finish(true);return;}r.on('data',b=>{if(done)return;if(!Buffer.isBuffer(b)||(total+=b.length)>max){finish(true);}else bits.push(b);});r.on('end',()=>finish(false,Buffer.concat(bits)));r.on('error',()=>finish(true));r.on('aborted',()=>finish(true));});req.on('error',()=>finish(true));req.end(second?undefined:body);}catch{finish(true);}};
  t=timer(()=>finish(true),60000);send(host,path,false);
 });
}
function release(v,a,id){if(!v||v.id!==id||v.tag_name!=='nm-ios18-'+a.operationId||v.target_commitish!==a.workflowCommit||v.draft!==false||v.prerelease!==true||!Array.isArray(v.assets)||v.assets.length>3)P.fail();const names=v.assets.map(v=>v.name);if(new Set(names).size!==names.length||names.some(x=>!['input-','claim-','output-'].some(p=>x===p+a.operationId+'.nmae')))P.fail();return v;}
async function download(a,id,assetId,sha256,bytes,token,ports={}){if(!Number.isSafeInteger(id)||id<1||!Number.isSafeInteger(assetId)||assetId<1||!P.SHA.test(sha256)||!Number.isSafeInteger(bytes)||bytes<1||bytes>MAX_CIPHER)P.fail();const call=ports.request||request,v=release(JSON.parse((await call('api.github.com','/repos/'+P.REPOSITORY+'/releases/'+id,'GET',null,token)).toString('utf8')),a,id),match=v.assets.filter(x=>x.id===assetId&&x.name==='input-'+a.operationId+'.nmae'&&x.size===bytes&&x.state==='uploaded');if(match.length!==1)P.fail();const b=await call('api.github.com','/repos/'+P.REPOSITORY+'/releases/assets/'+assetId,'GET',null,token);if(b.length!==bytes||P.sha(b)!==sha256)P.fail();return b;}
async function put(a,id,prefix,cipher,token,ports={}){if(!['claim','output'].includes(prefix)||!Buffer.isBuffer(cipher))P.fail();const call=ports.request||request,v=release(JSON.parse((await call('api.github.com','/repos/'+P.REPOSITORY+'/releases/'+id,'GET',null,token)).toString('utf8')),a,id),name=prefix+'-'+a.operationId+'.nmae';if(v.assets.some(x=>x.name===name))P.fail();const uploaded=JSON.parse((await call('uploads.github.com','/repos/'+P.REPOSITORY+'/releases/'+id+'/assets?name='+encodeURIComponent(name),'POST',cipher,token)).toString('utf8'));if(uploaded.name!==name||uploaded.size!==cipher.length||uploaded.state!=='uploaded'||!Number.isSafeInteger(uploaded.id)||uploaded.id<1||uploaded.digest&&uploaded.digest!=='sha256:'+P.sha(cipher))P.fail();return {assetId:uploaded.id,cipherBytes:cipher.length,cipherSha256:P.sha(cipher)};}
module.exports={MAX_CIPHER,redirect,request,release,download,put};
