'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const P=require('./policy.cjs'),S=require('./source-bundle.cjs'),E=require('./envelope.cjs'),F=require('./fixtures.cjs'),Pre=require('./preflight.cjs'),Operator=require('./operator.cjs'),Publisher=require('./publisher.cjs');
test('new target binds exact253 commit blobs and one13to18 overlay without changing original files',()=>{const f=F.source(),a=S.verifyFiles(f.manifest,f.files),z=S.overlay(a);assert.equal(P.SOURCE,'0f949de56eac3b01c73ed2a6a0b7f9601cf5729c');assert.equal(P.VERSION,18);assert.equal(S.COUNT,253);assert.equal(a.length,253);for(let i=0;i<a.length;i++){if(a[i].path==='app.config.ts'){assert.ok(a[i].bytes.toString().includes("buildNumber: '13'"));assert.ok(z[i].bytes.toString().includes("buildNumber: '18'"));assert.ok(z[i].bytes.toString().includes("CFBundleDevelopmentRegion: 'da'"));assert.ok(z[i].bytes.toString().includes('versionCode: 15'));assert.equal(z[i].bytes.toString().replace("buildNumber: '18'","buildNumber: '13'"),a[i].bytes.toString());}else assert.equal(z[i].bytes,a[i].bytes);}});
test('domain/version isolation keeps full AEAD authentication and rejects preceding native16 context',()=>{const a=F.approval(),k=Buffer.alloc(32,8),v={operationId:a.operationId,direction:'INPUT',workflowCommit:a.workflowCommit,sourceReviewSha256:a.sourceReviewSha256,nativeSource:P.SOURCE,backendSource:P.BACKEND_SOURCE,version:18};const x=E.seal(Buffer.from('test'),k,v,Buffer.alloc(12,8));assert.equal(E.open(x,k,v).toString(),'test');assert.throws(()=>E.open(x,k,{...v,version:16}));});
test('standalone operators and publication imports are pure until explicit authorized mode',async()=>{assert.equal((await Operator.main([])).credentialReads,0);assert.equal(Publisher.main([]).providerOperations,0);assert.throws(()=>Publisher.main(['--publish','bad']));});
test('Original Danish camera baseline and localization contract bind source truth while preserving byte algorithms',()=>{const py='C:/Users/runge/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe';const code="import ast,hashlib,json,pathlib; root=pathlib.Path(r'C:/Users/runge/.nevermonday-secrets/ios18-privacy-rules-final-20261009'); old=pathlib.Path(r'C:/Users/runge/.nevermonday-secrets/ios16-protected-github-macos-signature-capacity-20261006'); names=['executable','signature_capacity','signature_failure_shape','runtime_config_proof','bundle_runtime_proof','archive_runtime_proof','runtime_config_preflight','_unique_runtime_object','_invalid_runtime_constant']; tables=[{n.name:ast.dump(n,include_attributes=False) for n in ast.parse((p/'native-audit.py').read_text(encoding='utf-8-sig')).body if isinstance(n,ast.FunctionDef)} for p in [root,old]]; assert all(tables[0][n]==tables[1][n] for n in names); print(json.dumps({'immutableAlgorithms':len(names)}))";const r=cp.spawnSync(py,['-c',code],{shell:false,encoding:'utf8',maxBuffer:65536});assert.equal(r.status,0);assert.equal(JSON.parse(r.stdout).immutableAlgorithms,9);const feature=fs.readFileSync(path.join(__dirname,'feature_guard.py'),'utf8'),native=fs.readFileSync(path.join(__dirname,'native-audit.py'),'utf8');assert.ok(feature.includes("'cameraPurposeDanishExact': info.get('NSCameraUsageDescription') == DA_CAMERA"));assert.ok(feature.includes('Ingen billeder gemmes eller sendes.'));
assert.ok(native.includes('NSPrivacyCollectedDataTypePurposeDeveloperAdvertising'));assert.ok(native.includes("info.get('CFBundleDevelopmentRegion')=='da'"));assert.ok(native.includes("info.get('CFBundleVersion')=='18'"));});
test('immutable preflight expands exact reviewed workflow allowlist only with own18',()=>{assert.deepEqual(Pre.WORKFLOWS,['.github/workflows/nm-ios16-toolchain-probe.yml','.github/workflows/nm-protected-ios16.yml','.github/workflows/nm-protected-ios17.yml','.github/workflows/nm-protected-ios18.yml']);assert.equal(Pre.COUNT,57);assert.throws(()=>Pre.create({},null,{},null,null,P));});

test('actual operator dispatch entry accepts18 before any auth or provider access',async()=>{
 const vm=require('node:vm'),crypto=require('node:crypto'),bootstrapRaw=Buffer.from('fixture bootstrap');
 const reviewRaw=Buffer.from(JSON.stringify({files:[{file:'bootstrap.cjs',sha256:crypto.createHash('sha256').update(bootstrapRaw).digest('hex')}],sourceDependencies:[]}));
 const held={v:JSON.parse(reviewRaw),check:()=>{}},history={holdAll:()=>[],same:()=>{}},h={startup:()=>{},hold:()=>[],check:()=>{}};
 let exported=0,providerCalls=0;
 const fakeFs={readFileSync:file=>file.endsWith('source-review.json')?reviewRaw:file.endsWith('bootstrap.cjs')?bootstrapRaw:Buffer.from(JSON.stringify(F.approval())),mkdirSync:()=>{},writeFileSync:()=>{}};
 const modules={'node:fs':fakeFs,'node:path':path,'node:child_process':{spawnSync:()=>{providerCalls++;throw Error('UNEXPECTED_PROVIDER');}},'node:crypto':crypto,'./bootstrap.cjs':{hold:()=>held},'./held-source.cjs':h,'./policy.cjs':P,'./root-github.cjs':{},'./root-export.cjs':{execute:()=>{exported++;throw Error('UNEXPECTED_EXPORT');}},'./failed-operation-9c.cjs':history,'./preflight.cjs':{create:()=>({preflight:()=>{throw Error('PRE_AUTH_BOUNDARY_REACHED');},inspect:()=>null})}};
 const context={require:name=>{if(!(name in modules))throw Error('UNEXPECTED_IMPORT');return modules[name];},module:{exports:{}},__dirname,process:{env:{},execArgv:[],exitCode:0},console:{log:()=>{}},Buffer};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'operator.cjs'),'utf8'),context);
 const result=await context.module.exports.execute('a'.repeat(40),crypto.createHash('sha256').update(reviewRaw).digest('hex'));
 assert.equal(result.errorCode,'PRE_AUTH_BOUNDARY_REACHED');assert.equal(exported,0);assert.equal(providerCalls,0);
});

test('native audit checks and reports18 and historical workflow pins are explicit',()=>{
 const py='C:/Users/runge/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe';
 const code="import ast,json,pathlib; m=ast.parse(pathlib.Path('native-audit.py').read_text()); proof=[]; checks=[];\nfor n in ast.walk(m):\n if isinstance(n,ast.Dict):\n  for k,v in zip(n.keys,n.values):\n   if isinstance(k,ast.Constant) and k.value=='version' and isinstance(v,ast.Constant): proof.append(v.value)\n if isinstance(n,ast.Compare) and 'CFBundleVersion' in ast.unparse(n): checks.extend(c.value for c in n.comparators if isinstance(c,ast.Constant))\nassert proof==[18] and '18' in checks; print(json.dumps({'proofVersion':proof[0]}))";
 const result=cp.spawnSync(py,['-c',code],{cwd:__dirname,shell:false,encoding:'utf8'});assert.equal(result.status,0);assert.equal(JSON.parse(result.stdout).proofVersion,P.VERSION);
 assert.deepEqual(Pre.HISTORICAL.map(row=>({bytes:row.bytes,sha256:row.sha256})),[{bytes:1552,sha256:'0a344f726b6d9ce817f0efeb4a63b77488614c56b6f3b80ca60515a66cc09be8'},{bytes:2477,sha256:'0058da12bb6c6a30edf069a2ef0e0d076e166ca56973ae111a7c09b85a61d6e0'},{bytes:2477,sha256:'5d9f17ebbc4b58731691a0a6857468fb6da18d2d9b9f4b2089357764554ebb5f'}]);
});

test('source seal imports actual57 unique derived filenames without legacy receipt fields',()=>{
 const files=require('./seal-source.cjs').FILES;assert.equal(files.length,57);assert.equal(new Set(files).size,57);assert.ok(files.includes('protected-ios18.yml'));assert.ok(files.includes('ios18-target.test.cjs'));assert.ok(!files.includes('protected-ios17.yml'));
});
