'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const ROOT=__dirname,SOURCE='0f949de56eac3b01c73ed2a6a0b7f9601cf5729c',sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function code(e){const m=Object.getOwnPropertyDescriptor(e||{},'message')?.value;return typeof m==='string'&&/^[A-Z0-9_]{1,80}$/.test(m)?m:'OTHER_SUPPRESSED';}
async function execute(workflowCommit,expectedReview){const raw=fs.readFileSync(path.join(ROOT,'source-review.json'));if(sha(raw)!==expectedReview)throw Error('SOURCE_REVIEW_REFUSED');const bootstrapRow=JSON.parse(raw).files.find(r=>r.file==='bootstrap.cjs');if(sha(fs.readFileSync(path.join(ROOT,'bootstrap.cjs')))!==bootstrapRow.sha256)throw Error('SOURCE_REVIEW_REFUSED');const B=require('./bootstrap.cjs'),held=B.hold(ROOT,expectedReview),review=held.v,H=require('./held-source.cjs'),P=require('./policy.cjs'),GH=require('./root-github.cjs'),X=require('./root-export.cjs'),History=require('./failed-operation-9c.cjs');if(P.SOURCE!==SOURCE||P.VERSION!==18)throw Error('TARGET_REFUSED');H.startup(process.env,process.execArgv);const deps=H.hold(review.sourceDependencies,ROOT),history=History.holdAll(H.read),check=()=>{held.check();H.check(deps);History.same(history,H.read);};check();const id=crypto.randomUUID(),dir=path.join(ROOT,'protected',id);fs.mkdirSync(dir,{recursive:true,mode:0o700});const a={...JSON.parse(fs.readFileSync(path.join(ROOT,'approval-template.json'))),operationId:id,workflowCommit,sourceReviewSha256:expectedReview,environmentName:'nm-ios18-'+id},calls=[];let phase='SOURCE',key=null,secretMayExist=false,dispatched=false,cleaned=false,fresh=null,current=null;
 const ports={now:Date.now,check,invoke:(file,args,o)=>{check();const r=cp.spawnSync(file,args,o),n=calls.length+1,out=r.stdout||Buffer.alloc(0),err=r.stderr||Buffer.alloc(0);fs.writeFileSync(path.join(dir,'gh-'+n+'.stdout'),out,{flag:'wx',mode:0o600});fs.writeFileSync(path.join(dir,'gh-'+n+'.stderr'),err,{flag:'wx',mode:0o600});calls.push({n,operation:args[0]==='secret'?'SECRET_'+args[1]:args.find(x=>['GET','POST','PUT','PATCH'].includes(x))||'CLI',status:r.status,error:!!r.error,signal:r.signal,stdoutBytes:out.length,stdoutSha256:sha(out),stderrBytes:err.length,stderrSha256:sha(err)});check();return r;}};
 const record=v=>{const f=v.secretAbsentVerified?'key-cleanup.json':'dispatch-ack.json';fs.writeFileSync(path.join(dir,f),JSON.stringify(v,null,2)+'\n',{flag:'wx',mode:0o600});if(v.dispatchAcknowledged)dispatched=true;if(v.secretAbsentVerified)cleaned=true;};let environmentKnown=false,secretKnown=false;
 function preflight(tag){if(!fresh)fresh=require('./preflight.cjs').create(a,review,ports,GH,H,P,s=>phase=s);current=fresh.preflight(tag);if(tag&&environmentKnown)GH.verifyEnvironment(a,ports);if(tag&&secretKnown)GH.verifySecret(a,true,ports);if(tag)fresh.runAbsent();return current;}
 function absent(endpoint){const r=GH.cli(['api','--method','GET',endpoint],undefined,{...ports,invoke:(file,args,o)=>{const r=ports.invoke(file,args,o);if(r.status===1&&!r.error&&!r.signal&&Buffer.from(r.stderr).toString('utf8').includes('HTTP 404'))return {...r,status:0,stdout:Buffer.from('{"absent":true}'),stderr:Buffer.alloc(0)};return r;}});if(JSON.parse(r).absent!==true)throw Error('REMOTE_NAME_EXISTS');}
 let result;try{preflight(false);const at=new Date().toISOString();Object.assign(a,{authorized:true,rootReviewed:true,approvedAt:at,expiresAt:new Date(Date.parse(at)+600000).toISOString()});P.approval(a,Date.now());fs.writeFileSync(path.join(dir,'approval.json'),JSON.stringify(a,null,2)+'\n',{flag:'wx',mode:0o600});fs.writeFileSync(path.join(dir,'build-input.json'),fs.readFileSync(path.join(ROOT,'build-input-template.json')),{flag:'wx',mode:0o600});fs.writeFileSync(path.join(dir,'root-operation-once.json'),JSON.stringify({id,startedAt:at,source:SOURCE,version:18,noAutomaticRetry:true})+'\n',{flag:'wx'});console.log(JSON.stringify({stage:'IOS18_IMMUTABLE_SOURCE_VERIFIED',id,approvedAt:at,expiresAt:a.expiresAt,sourceFiles:253,helperFiles:review.files.length}));phase='EXPORT';const exp=await X.execute(id);check();if(exp.credentialQueryCount!==3||exp.versionQueryCount!==1||exp.remoteVersion!==15||exp.actualCiJobCreated!==false)throw Error('EXPORT_VERIFY');console.log(JSON.stringify({stage:'IOS18_EXISTING_SIGNER_SEALED',id,cipherBytes:exp.cipherBytes,remoteVersionObserved:15,versionMutation:false}));preflight(false);P.approval(a,Date.now());const extra={...ports,record,requireTagAndReleaseAbsent:()=>{absent('/repos/'+P.REPOSITORY+'/git/ref/tags/nm-ios18-'+id);absent('/repos/'+P.REPOSITORY+'/releases/tags/nm-ios18-'+id);},verifyRemoteSourceAndTag:()=>{preflight(true);P.approval(a,Date.now());},reserve:()=>fs.writeFileSync(path.join(dir,'github-dispatch-once.json'),JSON.stringify({id,startedAt:new Date().toISOString(),noAutomaticRetry:true})+'\n',{flag:'wx'}),environmentMustBeAbsent:async()=>absent('/repos/'+P.REPOSITORY+'/environments/'+a.environmentName),verifyEnvironmentPolicy:async()=>{GH.verifyEnvironment(a,ports);environmentKnown=true;},verifySecretNameOnly:async()=>{secretMayExist=true;GH.verifySecret(a,true,ports);secretKnown=true;},verifySecretAbsent:async()=>GH.verifySecret(a,false,ports)};phase='CIPHER_RELEASE';const release=GH.createCipherRelease(a,current,X.inputFile(dir,id),extra);fs.writeFileSync(path.join(dir,'cipher-release.json'),JSON.stringify(release,null,2)+'\n',{flag:'wx',mode:0o600});key=H.read(path.join(dir,'key.bin'),32);secretMayExist=true;phase='SECRET_DISPATCH';await GH.placeAndDispatch(a,current,key,release.releaseId,release.inputAsset,extra);check();result={kind:'ROOT_ACTUAL_PROTECTED_IOS18_DISPATCH',operationId:id,workflowCommit,source:SOURCE,version:18,sourceReviewSha256:expectedReview,dispatchAcknowledged:dispatched,releaseId:release.releaseId,inputAsset:release.inputAsset,environmentName:a.environmentName,paidRunner:false,keyDeletionPending:true,buildVerified:false,rawSecretsPrinted:0,noAutomaticRetry:true};
 }catch(e){result={kind:'ROOT_ACTUAL_PROTECTED_IOS18_DISPATCH_FAILED',operationId:id,phase,errorCode:code(e),dispatchAcknowledged:dispatched,secretMayExist,detailsSuppressed:true};if(secretMayExist){try{await GH.deleteKey(a,{...ports,record,verifySecretAbsent:async()=>GH.verifySecret(a,false,ports)});}catch(x){result.cleanupErrorCode=code(x);}}result.secretAbsentVerified=cleaned;process.exitCode=1;}finally{key?.fill(0);}const proof={...result,finishedAt:new Date().toISOString(),callRows:calls,immutableSource:fresh?.inspect()};fs.writeFileSync(path.join(dir,'root-dispatch-proof.json'),JSON.stringify(proof,null,2)+'\n',{flag:'wx',mode:0o600});console.log(JSON.stringify(result));return result;
}
function main(args=[]){if(!args.length)return Promise.resolve({preparedOnly:true,providerOperations:0,credentialReads:0});if(args.length!==3||args[0]!=='--dispatch'||!/^[a-f0-9]{40}$/.test(args[1])||!/^[a-f0-9]{64}$/.test(args[2]))throw Error('ARGUMENTS_REFUSED');return execute(args[1],args[2]);}
module.exports={code,execute,main};if(require.main===module)Promise.resolve().then(()=>main(process.argv.slice(2))).then(v=>{if(v?.preparedOnly)console.log(JSON.stringify(v));}).catch(e=>{console.log(JSON.stringify({dispatch:false,errorCode:code(e),detailsSuppressed:true}));process.exitCode=1;});
