'use strict';
// Publish only reviewed source helpers; preserve every existing remote tree entry.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),cp=require('node:child_process');
const ROOT=__dirname,REPO='rungerunge/loyalino-test',GH='C:/Program Files/GitHub CLI/gh.exe',sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function main(args=[]){if(!args.length)return{preparedOnly:true,providerOperations:0};if(args.length!==2||args[0]!=='--publish'||!/^[a-f0-9]{64}$/.test(args[1]))throw Error('PUBLICATION_ARGS_REFUSED');const raw=fs.readFileSync(ROOT+'/source-review.json');if(sha(raw)!==args[1])throw Error('PUBLICATION_SOURCE_REFUSED');const review=JSON.parse(raw),B=require('./bootstrap.cjs'),held=B.hold(ROOT,args[1]),scan=JSON.parse(fs.readFileSync(ROOT+'/public-source-scan.json'));if(scan.exitCode!==0||scan.findings!==0||scan.sourceReviewSha256!==args[1]||review.files.length!==57)throw Error('PUBLICATION_SCAN_REFUSED');const check=()=>held.check();let n=0;const id=crypto.randomUUID(),logDir=ROOT+'/publication-'+id;fs.mkdirSync(logDir,{mode:0o700});function api(method,endpoint,body){check();const argv=['api','--method',method,endpoint];if(body!==undefined)argv.push('--input','-');const r=cp.spawnSync(GH,argv,{input:body===undefined?undefined:JSON.stringify(body),shell:false,encoding:null,timeout:60000,maxBuffer:8*1024*1024,windowsHide:true});n++;fs.writeFileSync(logDir+'/call-'+n+'.stdout',r.stdout||Buffer.alloc(0),{flag:'wx'});fs.writeFileSync(logDir+'/call-'+n+'.stderr',r.stderr||Buffer.alloc(0),{flag:'wx'});check();if(r.status!==0||r.error||r.signal||r.stderr?.length)throw Error('PUBLICATION_API_REFUSED');return r.stdout.length?JSON.parse(r.stdout):null;}
 function authority(){const u=api('GET','/user'),r=api('GET','/repos/'+REPO),p=api('GET','/repos/'+REPO+'/actions/permissions'),c=api('GET','/repos/'+REPO+'/collaborators?per_page=100'),i=api('GET','/repos/'+REPO+'/invitations?per_page=100');if(u.login!=='rungerunge'||r.private!==false||r.archived||r.disabled||r.permissions?.admin!==true||!p.enabled||p.allowed_actions!=='all'||c.length!==1||c[0].login!=='rungerunge'||i.length)throw Error('PUBLICATION_AUTHORITY_REFUSED');return api('GET','/repos/'+REPO+'/git/ref/heads/main').object.sha;}
 const start=authority(),commit=api('GET','/repos/'+REPO+'/git/commits/'+start),tree=api('GET','/repos/'+REPO+'/git/trees/'+commit.tree.sha+'?recursive=1');if(tree.truncated!==false||tree.tree.length>1000||tree.tree.some(r=>r.path.startsWith('.github/protected-ios18/')||r.path==='.github/workflows/nm-protected-ios18.yml'))throw Error('PUBLICATION_TARGET_EXISTS');const paths=review.files.map(r=>({source:r.file,target:'.github/protected-ios18/'+r.file,bytes:r.bytes,sha256:r.sha256}));paths.push({source:'source-review.json',target:'.github/protected-ios18/source-review.json',bytes:raw.length,sha256:sha(raw)});const w=review.files.find(r=>r.file==='protected-ios18.yml');paths.push({source:w.file,target:'.github/workflows/nm-protected-ios18.yml',bytes:w.bytes,sha256:w.sha256});fs.writeFileSync(logDir+'/intent.json',JSON.stringify({id,start,sourceReviewSha256:args[1],files:paths.length,scopedPrefix:'.github/protected-ios18/',providerAppSourceWrites:0,startedAt:new Date().toISOString()},null,2)+'\n',{flag:'wx'});
 const entries=[];for(const p of paths){const b=fs.readFileSync(ROOT+'/'+p.source);if(b.length!==p.bytes||sha(b)!==p.sha256)throw Error('PUBLICATION_SOURCE_REFUSED');const v=api('POST','/repos/'+REPO+'/git/blobs',{content:b.toString('base64'),encoding:'base64'});const expected=crypto.createHash('sha1').update(Buffer.from('blob '+b.length+'\0')).update(b).digest('hex');if(v.sha!==expected)throw Error('PUBLICATION_BLOB_REFUSED');entries.push({path:p.target,mode:'100644',type:'blob',sha:v.sha});if(entries.length%10===0)console.log(JSON.stringify({stage:'PUBLIC_HELPER_BLOBS',files:entries.length,total:paths.length}));}
 const nextTree=api('POST','/repos/'+REPO+'/git/trees',{base_tree:commit.tree.sha,tree:entries}),nextCommit=api('POST','/repos/'+REPO+'/git/commits',{message:'Prepare protected NeverMonday iOS18 with original UI and corrected privacy purposes',tree:nextTree.sha,parents:[start]});if(authority()!==start)throw Error('PUBLICATION_CONCURRENT_CHANGE');api('PATCH','/repos/'+REPO+'/git/refs/heads/main',{sha:nextCommit.sha,force:false});if(authority()!==nextCommit.sha)throw Error('PUBLICATION_READBACK_REFUSED');const after=api('GET','/repos/'+REPO+'/git/trees/'+nextTree.sha+'?recursive=1');if(after.truncated!==false)throw Error('PUBLICATION_READBACK_REFUSED');const map=new Map(after.tree.map(r=>[r.path,r]));for(const r of tree.tree){const z=map.get(r.path);if(r.type==='blob'&&(!z||z.sha!==r.sha||z.mode!==r.mode||z.type!==r.type))throw Error('PUBLICATION_REMOTE_CONTENT_CHANGED');}for(const r of entries){const z=map.get(r.path);if(!z||z.sha!==r.sha||z.mode!=='100644'||z.type!=='blob')throw Error('PUBLICATION_READBACK_REFUSED');}
 const result={kind:'IOS18_SCOPED_PUBLIC_HELPER_PUBLICATION',id,workflowCommit:nextCommit.sha,priorCommit:start,sourceReviewSha256:args[1],helperFiles:paths.length,remoteBlobsPreserved:tree.tree.filter(r=>r.type==='blob').length,plainAppSourcePublished:false,signerPublished:false,secretsPublished:false,finishedAt:new Date().toISOString()};fs.writeFileSync(logDir+'/result.json',JSON.stringify(result,null,2)+'\n',{flag:'wx'});fs.writeFileSync(ROOT+'/publication-result.json',JSON.stringify(result,null,2)+'\n',{flag:'wx'});return result;
}
module.exports={main};if(require.main===module){try{console.log(JSON.stringify(main(process.argv.slice(2))));}catch(e){console.log(JSON.stringify({publication:false,errorCode:/^[A-Z_]+$/.test(e.message)?e.message:'OTHER_SUPPRESSED'}));process.exitCode=1;}}
