'use strict';
// Fictional signing/account/query values. Only exact committed public Git blobs
// are read when source() is explicitly called; never workspace/private inputs.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),cp=require('node:child_process'),P=require('./policy.cjs');
const NOW=Date.parse('2026-10-06T00:00:00.000Z'),ID='abcdef12-1234-4234-8234-abcdef123456',H=n=>n.toString(16).repeat(64),OWNER='synthetic-owner';
function approval(manifestSha=H(6)){return{kind:'ROOT_PROTECTED_IOS18_CI_APPROVAL',authorized:true,rootReviewed:true,operationId:ID,approvedAt:new Date(NOW).toISOString(),expiresAt:new Date(NOW+600000).toISOString(),sourceReviewSha256:H(1),workflowCommit:'a'.repeat(40),nativeSource:P.SOURCE,backendSource:P.BACKEND_SOURCE,project:P.PROJECT,account:P.ACCOUNT,bundle:P.BUNDLE,team:P.TEAM,version:18,ownerAccountSha256:P.sha(OWNER),certificateSerialSha256:P.sha('ABCDEF12'),profileUuidSha256:P.sha('11111111-2222-3333-4444-555555555555'),referenceSigningProofSha256:H(5),publicSourceManifestSha256:manifestSha,xcodeVersion:P.TOOLCHAIN.xcode,iosSdkVersion:P.TOOLCHAIN.iosSdk,environmentName:'nm-ios18-'+ID,noAutomaticRetry:true};}
function queries(){const ownerAccount={id:OWNER,name:P.ACCOUNT},appleTeam={id:'synthetic-team',appleTeamIdentifier:P.TEAM},appleAppIdentifier={id:'synthetic-identifier',bundleIdentifier:P.BUNDLE};const identity={app:{byId:{id:P.PROJECT,ownerAccount,iosAppCredentials:[{id:'synthetic-credentials',appleTeam,appleAppIdentifier}]}}};const cert={id:'synthetic-cert',serialNumber:'ABCDEF12',validityNotBefore:'2026-01-01T00:00:00.000Z',validityNotAfter:'2027-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z',appleTeam,account:ownerAccount},profile={id:'synthetic-profile',appleUUID:'11111111-2222-3333-4444-555555555555',expiration:'2027-01-01T00:00:00.000Z',status:'ACTIVE',updatedAt:'2026-01-01T00:00:00.000Z',appleTeam,account:ownerAccount,appleAppIdentifier};const metadata={app:{byId:{id:P.PROJECT,ownerAccount,iosAppCredentials:[{id:'synthetic-credentials',appleTeam,appleAppIdentifier,iosAppBuildCredentialsList:[{id:'synthetic-build',iosDistributionType:'APP_STORE',distributionCertificate:cert,provisioningProfile:profile}]}]}}};const material=structuredClone(metadata),b=material.app.byId.iosAppCredentials[0].iosAppBuildCredentialsList[0];b.distributionCertificate.certificateP12=Buffer.from('synthetic-p12').toString('base64');b.distributionCertificate.certificatePassword='synthetic-only';b.provisioningProfile.provisioningProfile=Buffer.from('synthetic-cms').toString('base64');return {VERSION:{app:{byId:{id:P.PROJECT,latestAppVersionByPlatformAndApplicationIdentifier:{id:'synthetic-version',storeVersion:'1.0.0',buildVersion:'15'}}}},IDENTITY:identity,METADATA:metadata,MATERIAL:material};}
let cached;
function source(){if(cached)return cached;const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'public-source-manifest.json'))),r=cp.spawnSync('git',['archive','--format=tar',P.SOURCE,'mobile'],{cwd:'C:/Users/runge/Desktop/nevermonday app',encoding:null,shell:false,maxBuffer:16*1024*1024,timeout:30000});if(r.status!==0||r.error||r.signal||r.stderr.length)throw Error('PUBLIC_GIT_FIXTURE_REFUSED');const byPath=new Map();for(let at=0;at+512<=r.stdout.length;){const h=r.stdout.subarray(at,at+512);if(h.every(x=>x===0))break;const name=h.subarray(0,100).toString('utf8').split('\0')[0],size=parseInt(h.subarray(124,136).toString().split('\0')[0].trim(),8),type=h[156];if(type===48||type===0)byPath.set(name.slice(7),r.stdout.subarray(at+512,at+512+size));at+=512+Math.ceil(size/512)*512;}const files=manifest.files.map(v=>({path:v.path,base64:byPath.get(v.path).toString('base64')}));cached={manifest,files};return cached;}
const publicEnv={EXPO_PUBLIC_API_BASE:'https://backend-production-d356.up.railway.app/api/mobile/v1',EXPO_PUBLIC_SHOP_DOMAIN:'never-monday.myshopify.com',EXPO_PUBLIC_STOREFRONT_TOKEN:''};
module.exports={NOW,ID,H,OWNER,approval,queries,source,publicEnv};
