'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),P=require('./policy.cjs'),L=require('./lineage.cjs');
const T=Date.parse('2026-10-06T00:00:00.000Z'),H=n=>n.toString(16).repeat(64),copy=v=>structuredClone(v);
function fixture(){const a={kind:'ROOT_PROTECTED_IOS18_CI_APPROVAL',authorized:true,rootReviewed:true,operationId:'abcdef12-1234-4234-8234-abcdef123456',approvedAt:new Date(T).toISOString(),expiresAt:new Date(T+600000).toISOString(),sourceReviewSha256:H(1),workflowCommit:'a'.repeat(40),nativeSource:P.SOURCE,backendSource:P.BACKEND_SOURCE,project:P.PROJECT,account:P.ACCOUNT,bundle:P.BUNDLE,team:P.TEAM,version:18,ownerAccountSha256:H(2),certificateSerialSha256:H(3),profileUuidSha256:H(4),referenceSigningProofSha256:H(5),publicSourceManifestSha256:H(6),xcodeVersion:P.TOOLCHAIN.xcode,iosSdkVersion:P.TOOLCHAIN.iosSdk,environmentName:'nm-ios18-abcdef12-1234-4234-8234-abcdef123456',noAutomaticRetry:true},e={runId:1234567890,inputCipherSha256:H(7),inputCipherBytes:2000000,outputCipherSha256:H(8),outputCipherBytes:25000000,ipaSha256:H(9),ipaBytes:24999900,rootNativeAuditSha256:H(10)},r={kind:'ROOT_IOS18_PROTECTED_GITHUB_CI_BUILD',operationId:a.operationId,repository:P.REPOSITORY,actor:P.ACTOR,event:'workflow_dispatch',workflowCommit:a.workflowCommit,runId:e.runId,runAttempt:1,runnerLabel:P.RUNNER,runnerOs:'macOS',environmentName:a.environmentName,nativeSource:P.SOURCE,backendSource:P.BACKEND_SOURCE,mobileFilesCount:253,version:18,bundle:P.BUNDLE,team:P.TEAM,startedAt:new Date(T+1000).toISOString(),finishedAt:new Date(T+2400000).toISOString(),xcodeVersion:a.xcodeVersion,iosSdkVersion:a.iosSdkVersion,toolchainSha256:P.TOOLCHAIN_SHA,inputCipherSha256:e.inputCipherSha256,inputCipherBytes:e.inputCipherBytes,outputCipherSha256:e.outputCipherSha256,outputCipherBytes:e.outputCipherBytes,ipaSha256:e.ipaSha256,ipaBytes:e.ipaBytes,sourceManifestSha256:a.publicSourceManifestSha256,certificateSerialSha256:a.certificateSerialSha256,profileUuidSha256:a.profileUuidSha256,referenceSigningProofSha256:a.referenceSigningProofSha256,rootNativeAuditSha256:e.rootNativeAuditSha256,...Object.fromEntries(L.TRUE_FLAGS.map(k=>[k,true])),...Object.fromEntries(L.FALSE_FLAGS.map(k=>[k,false])),easCloudBuildId:null};return{a,e,r,now:T+2401000,run(){return L.validate(this.r,this.a,this.e,this.now);}};}
test('genuine-format protected GitHub build lineage binds independent expected artifact evidence only',()=>{const f=fixture(),v=f.run();assert.equal(v.lineageVerified,true);assert.equal(v.runAttempt,1);assert.equal(v.runId,f.e.runId);assert.equal(v.ipaSha256,f.e.ipaSha256);assert.equal(v.rootNativeAuditReferenceBound,true);assert.equal(v.nativeAuditPerformedByThisVerifier,false);assert.equal(v.nativeAuditVerifiedByThisVerifier,false);for(const k of ['easFinishedVerified','easCloudJobCreated','testFlightSubmitted','physicalVerified','readinessVerified','productionReady'])assert.equal(v[k],false);assert.equal(Object.isFrozen(v),true);assert.equal(Object.hasOwn(v,'certificateSerial'),false);});
for(const[k,value]of [['kind','EAS_FINISHED'],['repository','rungerunge/other'],['actor','other'],['event','push'],['workflowCommit','b'.repeat(40)],['runId',0],['runAttempt',2],['runnerLabel',P.RUNNER+'-large'],['runnerLabel',P.RUNNER+'-xlarge'],['runnerLabel','macos-15'],['runnerOs','Linux'],['environmentName','nm-other'],['nativeSource','b'.repeat(40)],['backendSource','b'.repeat(40)],['mobileFilesCount',248],['version','18'],['version',15],['bundle','dk.other.app'],['team','OTHERTEAM'],['xcodeVersion','26.0'],['iosSdkVersion','26.0'],['toolchainSha256',H(11)],['sourceManifestSha256',H(11)],['certificateSerialSha256',H(11)],['profileUuidSha256',H(11)],['referenceSigningProofSha256',H(11)],['easCloudBuildId','aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee']])test('strict lineage rejects '+k+' '+String(value),()=>{const f=fixture();f.r[k]=value;assert.throws(()=>f.run(),/PROTECTED_IOS18_CI_REFUSED/);});
for(const k of L.TRUE_FLAGS)test('independent audit requirement refuses false/nonbool '+k,()=>{for(const v of [false,1,'true']){const f=fixture();f.r[k]=v;assert.throws(()=>f.run());}});
for(const k of L.FALSE_FLAGS)test('no public/paid/fallback/physical promotion '+k,()=>{for(const v of [true,0,'false']){const f=fixture();f.r[k]=v;assert.throws(()=>f.run());}});
for(const k of L.EXPECTED)test('root receiver exact binding prevents CI selfassertion '+k,()=>{const f=fixture();f.r[k]=typeof f.r[k]==='number'?f.r[k]+1:H(12);assert.throws(()=>f.run());});
for(const [name,edit]of [['missing-independent',f=>f.e=null],['unknown-expected',f=>f.e.acceptNativeAudit=true],['expiry-knob',f=>f.e.maxAgeMs=999999999],['unreviewed-workflow-field',f=>f.r.workflowYaml='PRIVATE'],['EAS-job-alias',f=>f.r.jobId='PRIVATE'],['public-IPA-body',f=>f.r.ipaBase64='PRIVATE']])test('exact closed shapes reject '+name,()=>{const f=fixture();edit(f);assert.throws(()=>f.run());});
test('start must lie within genuine600s approval while long build completion remains separate',()=>{const f=fixture();assert.ok(f.now>Date.parse(f.a.expiresAt));assert.equal(f.run().lineageVerified,true);for(const t of [T-1,T+600000]){const g=fixture();g.r.startedAt=new Date(t).toISOString();assert.throws(()=>g.run());}});
test('fresh completion strict1800000 boundary and canonical chronology',()=>{const f=fixture();f.now=Date.parse(f.r.finishedAt)+1799999;assert.equal(f.run().lineageVerified,true);f.now++;assert.throws(()=>f.run());for(const edit of [g=>g.r.finishedAt=new Date(g.now+1).toISOString(),g=>g.r.finishedAt=new Date(T).toISOString(),g=>g.r.startedAt=g.r.startedAt.replace('.000Z','Z'),g=>g.now=NaN]){const g=fixture();edit(g);assert.throws(()=>g.run());}});
test('approval old/extra/default authorizations cannot claim lineage',()=>{for(const edit of [a=>a.authorized=false,a=>a.rootReviewed=false,a=>a.workflowCommit='0'.repeat(40),a=>a.expiresAt=new Date(T+900000).toISOString(),a=>a.extra=true]){const f=fixture();edit(f.a);assert.throws(()=>f.run());}});
test('cipher/IPA/hash bounds reject zero/oversize/placeholder receiver authority',()=>{for(const [k,v]of [['inputCipherBytes',0],['outputCipherBytes',2147483649],['ipaBytes',999999],['ipaBytes',536870913],['inputCipherSha256','0'.repeat(64)],['rootNativeAuditSha256','g'.repeat(64)],['runId',NaN]]){const f=fixture();f.e[k]=v;f.r[k]=v;assert.throws(()=>f.run());}});
module.exports={fixture};
